Added solutions to many exercices and improved the forms chapter
worldline/angular-training pull request #23
Opened 2021-08-05 08:54 UTC by yostane

2021-08-21 08:07 UTC, Ocunidee requested changes

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/directives/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-property-binding-training-e4kqd9?file=src%2Fapp%2Fapp.component.html).*
Cette  correction rajoute des éléments par rapport à l'énoncé qui peuvent amené de la confusion - le fait de changer le style (surtout que le style ne peut être changé qu'une fois mais que le bouton reste visible) - peut être ne proposer que la correction stricte de l'exercice.

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/components/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-input-training-books?file=src%2Fapp%2Fapp.component.html).*
Proposer des corrections est une très bonne idée par contre je serai pour qu'elles ne figurent pas directement dans les chapitres. Psychologiquement, ça incite pas à chercher par soi-même et c'est vraiment dommage sachant que ce sont des purs exercices d'application très simples. Il serait vraiment bien qu'on leur donne à la fin de la formation si les stagiaires veulent faire des révisions plus tard. On pourrait avoir une page spécifique pour (faudrait pas qu'elle soit facilement visible si on l'intègre directement au vuepress)

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/directives/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-attribute-directive-training-pbg89t?file=src%2Fapp%2Fapp.component.html).*
Pour le 3ème fantôme il faudrait utiliser [class.wobbly]="ghost3.isWobbly"

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/directives/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-attribute-directive-training-pbg89t?file=src%2Fapp%2Fapp.component.html).*
ça semble pas être le correctif de cet exercices mais de l'exercice sur les fantômes

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/directives/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-ngif-training-vna4zk?file=src%2Fapp%2Fapp.component.html).*
Il manque la correction de la première partie de l'énoncé "use an NgIf to toggle the loader"
<app-loader *ngIf="isLoading"></app-loader>

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/directives/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-ngswitch-training-plant-temperature).*
Le but de ce chapitre est de travailler au maximum via les directives et donc dans l'html
Voici une correction qui ne touche pas la classe ts:
  <ng-container [ngSwitch]="true">
    <span *ngSwitchCase="temperature < 20">🍂</span>
    <span *ngSwitchCase="temperature >= 20 && temperature < 30">🌱</span>
    <span *ngSwitchDefault>🌻</span>
  </ng-container>

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/forms/README.md
> +## Sources and goind further
type goind => going

2021-08-21 08:07 UTC, Ocunidee commented on docs/src/pipes/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-currency-pipe-training-example-eur-pm7dqd?file=src%2Fapp%2Fexample.pipe.ts).*
The exemple.pipe.ts file should be deleted from the correction

Pour montrer le plein intérêt du pipe de date et à quel point il marche bien avec les locale, ne pas forcer le format via 'EEEE MMMM y' mais utiliser le format 'fullDate', ce dernier s'adapte au différence d'habitude de rédaction des dates en fonction de la locale et ne fait pas que de la "traduction": Par exemple {{expirationDate | date:'fullDate'}} donne pour en-US: Monday, August 23, 2021 et pour de: Montag, 23. August 2021 (la ponctuation et l'ordre des éléments sont adaptés à chaque locale)

2021-08-31 10:00 UTC, wlybe commented on docs/src/components/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-input-training-books?file=src%2Fapp%2Fapp.component.html).*
Ptet mettre les urls des correction dans un ficher et mettre ce dernier dans le dossier "corrections".

2021-09-12 06:18 UTC, Ocunidee commented on docs/src/components/README.md
> +*A correction is available [here](https://stackblitz.com/edit/angular-input-training-books?file=src%2Fapp%2Fapp.component.html).*
oui c'est une bonne idée :)

2022-02-18 18:04 UTC, wlybe commented
Je vais fermer cette branche car c ptet mieux d'avoir des corrections ouvertes. Merci pour les retours

2022-02-18 18:04 UTC, closed without merging