draft: Migrate bootstrap to angular12 and eslint
worldline/angular-training pull request #25
Opened 2021-08-06 13:27 UTC by yostane

```
ng update @angular/core@12 @angular/cli@12
ng add @angular-eslint/schematics
 ng g @angular-eslint/schematics:convert-tslint-to-eslint
```

2021-10-29 16:58 UTC, Ocunidee requested changes

2021-10-29 16:58 UTC, Ocunidee commented on corrections/7-http-calls/search-films/src/app/models/authentication/user-response.ts
> +    /* eslint-disable @typescript-eslint/naming-convention, no-underscore-dangle, id-blacklist, id-match */
il ne semble pas être nécessaire de désactiver de règles eslint, created_at passe le linter chez moi sans le commentaire à la ligne 14.

Si tu confirmes pour toi aussi, alors tu peux supprimer les 3 occurrences de ce commentaire

2021-10-29 16:58 UTC, Ocunidee commented on docs/src/first-steps/README.md
> +- `.eslintrc.json.`: the default ESLint configuration of the workspace
```suggestion
- `.eslintrc.json`: the default ESLint configuration of the workspace
```

2021-10-29 16:58 UTC, Ocunidee commented on docs/src/tooling/README.md
> +npm install -g @angular/cli@12
afin d'être cohérent avec les corrections proposées, on peut proposer d'installer la version 12.2.11

2021-10-29 16:58 UTC, Ocunidee commented on docs/src/tooling/README.md
> -First, install the linter [TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin). Even though it is now deprecated, the Angular CLI is still using it
Comme pour TSLint, il faut installer l'extension ESLint dans VSCode pour avoir le surlignage des erreurs. Voici son lien: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

2021-11-12 14:17 UTC, wlybe commented on docs/src/tooling/README.md
> -First, install the linter [TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin). Even though it is now deprecated, the Angular CLI is still using it
bien vu !. Je vais le rajouter dans la partie light installation, car le pack de John Papa l'intègre déjà

2022-02-04 13:13 UTC, Ocunidee approved these changes

2022-02-04 13:14 UTC, merged