Training in french
worldline/angular-training pull request #26
Opened 2021-09-23 11:22 UTC by Sowtch

From the basic training in English, I made a translation of the Angular training in French! 😄

2021-09-24 07:26 UTC, Ocunidee commented
> From the basic training in English, I made a translation of the Angular training in French! 😄

Thank you for your contribution, I'll review it shortly, most likely next week :)

2021-09-24 14:30 UTC, Sowtch commented
You're welcome 😄

2021-10-29 11:04 UTC, Ocunidee requested changes
Hello !

Ta traduction est de très grande qualité et merci beaucoup pour ta contribution. :)

Je t'ai fait des suggestions de modification que tu peux prendre en compte directement dans l'interface de github (pas besoin de changer les fichiers en local). Il n'y aura normalement que le fichier package-lock.json que tu auras à traiter en local.

Si mes suggestions te conviennent, je t'invite à les accepter et à les commiter en une seule fois (ça va faire bcp de mini commit sinon ^^"). Github fournit un bouton pour accepter une suggestion en l'ajoutant à un batch.

Pourras-tu par la suite rebase ta branche sur la branche main de l'upstream?

Merci d'avance!

2021-10-29 11:04 UTC, Ocunidee commented on docs/package-lock.json
> +  "lockfileVersion": 1,
Discard tous les changements du package-lock.json. Tu dois utiliser une version de npm plus ancienne que celle utilisée pour générer le package-lock initial, d'où le passage à la version 1 ;)

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/index.md
> +  - title: Bibliothèque
```suggestion
  - title: Librairies officielles
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/index.md
> +    details: Plongez dans Angular Router, les formulaires et HttpClient
Forms c'est le nom de la librairie, on la rajoute à un projet via @angular/forms, du coup on va garder son nom anglais:
```suggestion
    details: Plongez dans Angular Router, Forms et HttpClient
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/index.md
> +    details: Développez des applications Angular directement à partir d'une commande shell
```suggestion
    details: Développez des applications Angular directement en ligne de commande
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/index.md
> +- Connaissance de base en JavaScript
```suggestion
- Connaissances de base en JavaScript
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/index.md
> +- Connaissance de base en HTML & CSS
```suggestion
- Connaissances de base en HTML & CSS
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +Angular est plus qu'un simple framework frontend avec lequel créer des applications à page unique (Single Page Applications : SPA). Il s'agit d'une plate-forme de développement à part entière constru
On va garder les termes anglais pour les termes techniques
```suggestion
Angular est plus qu'un simple framework frontend avec lequel créer des SPA (Single Page Applications). Il s'agit d'une plate-forme de développement à part entière construite en TypeScript qui comprend :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Un framework basé sur des composants pour créer des applications Web évolutives.
```suggestion
- Un framework basé sur des composants pour créer des applications Web scalables.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Une collection de bibliothèques bien intégrées qui couvrent une grande variété de fonctionnalités, notamment le routage, la gestion des formulaires, la communication client-serveur, les application
```suggestion
- Une collection de librairies bien intégrées qui couvrent une grande variété de fonctionnalités, notamment le routage, la gestion des formulaires, la communication client-serveur, les progressive web apps, etc.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Une suite d'outils de développement pour vous aider à développer, créer, tester et mettre à jour votre code via Angular CLI.
```suggestion
- Une suite d'outils de développement pour vous aider à développer, créer, tester et mettre à jour votre code via le CLI Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +  - Les données sont extraites dynamiquement du serveur lorsque le client en a besoin
```suggestion
  - Les données sont récupérées dynamiquement du serveur lorsque le client en a besoin
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +    - It is not necessary to provide an API Il n'est pas nécessaire de fournir une API (par exemple, un jeu vidéo sur SPA)
```suggestion
    - Il n'est pas nécessaire de fournir une API (par exemple, un jeu vidéo sur SPA)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +  - Ce modèle est similaire à celui utilisé dans les applications mobiles (le SPA est analogue à l'application mobile)
```suggestion
  - Ce modèle est similaire à celui utilisé dans les applications mobiles (la SPA est analogue à l'application mobile)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +Une application Angular est un *SPA* qui est complété par une API si besoin.
```suggestion
Une application Angular est une *SPA* qui est complété par une API si besoin.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +Chaque cadre a ses propres forces et faiblesses.
```suggestion
Chaque framework a ses propres forces et faiblesses.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Il est particulièrement bien adapté aux projets qui doivent évoluer et à cet effet, il est principalement utilisé pour les projets d'entreprise.
```suggestion
- Il est particulièrement bien adapté aux projets qui doivent scale et à cet effet, il est principalement utilisé pour les projets d'entreprise.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Son riche écosystème de bibliothèques officielles permet une grande cohérence entre les projets, ce qui signifie que lors du transfert d'équipes ou de projets, vous n'aurez besoin que de vous rense
```suggestion
- Son riche écosystème de librairies officielles permet une grande cohérence entre projets, ce qui signifie que lors d'un changement d'équipes ou de projets, vous n'aurez besoin que de monter en compétences sur le nouveau domaine d'activité et non sur une façon différente de développer, car, par exemple,  un autre choix de librairies aura été fait.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- Il est très bien documenté et la cohérence dans la manière dont le cadre est utilisé signifie que vous êtes plus que susceptible de trouver une réponse à toutes les questions que vous pourriez renc
```suggestion
- Il est très bien documenté et la cohérence dans la manière dont le framework est utilisé signifie que vous êtes plus que susceptible de trouver en ligne des réponses à toutes les questions que vous pourriez rencontrer au cours de votre parcours d'apprentissage.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/presentation/README.md
> +- L'équipe Angular est très fière de la facilité avec laquelle elle facilite la mise à jour des projets Angular, en fournissant des étapes faciles à suivre et une migration entièrement automatisée.
```suggestion
- L'équipe Angular est très fière de la manière avec laquelle elle facilite la mise à jour des projets Angular, en fournissant des étapes faciles à suivre et une migration entièrement automatisée.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +En Java ou C#, toute valeur ou objet donné a un type exact - soit null, une primitive ou un type de classe connu. Nous pouvons appeler des méthodes telles que `value.GetType()` ou `value.getClass()`
```suggestion
En Java ou C#, toute valeur ou objet donné a un type exact - soit null, une primitive ou un type de classe connu. Nous pouvons appeler des méthodes telles que `value.GetType()` ou `value.getClass()` pour récupérer le type exact au runtime. La définition de ce type résidera dans une classe quelque part avec un nom, et nous ne pouvons pas utiliser deux classes avec des formes similaires à la place l'une de l'autre à moins qu'il n'y ait une relation d'héritage explicite ou une interface implémentée par les deux.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +La variable `force` n'est jamais déclarée comme étant de type Point. Cependant, TypeScript compare la forme de la force à la forme du point dans la vérification de type. Ils ont la même forme, donc l
```suggestion
La variable `force` n'est jamais déclarée comme étant de type Point. Cependant, lors de la vérification de type, TypeScript compare la forme de `force` à la forme de `Point`. Ils ont la même forme, donc le code passe.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Le système de types de TypeScript n'est pas non plus *réifié* : il n'y a rien au moment de l'exécution qui nous dira que `force` est Point. En fait, le type Point n'est présent sous aucune forme à l'
```suggestion
Le système de types de TypeScript n'est pas non plus *réifié* : il n'y a rien au runtime qui nous dira que `force` est Point. En fait, le type Point n'est présent sous aucune forme à l'exécution.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +La correspondance de forme ne nécessite qu'un sous-ensemble des champs de l'objet pour correspondre.
```suggestion
La concordance des formes marchent même si uniquement un sous-ensemble des champs de l'objet correspond.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Il n'y a pas de différence entre la façon dont les classes et les objets se conforment aux formes :
```suggestion
Il n'y a pas de différence dans la façon dont les classes et les objets se conforment aux formes :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Si l'objet ou la classe possède toutes les propriétés requises, TypeScript dira qu'elles correspondent, quels que soient les détails de l'implémentation.
```suggestion
Si l'objet ou la classe possède toutes les propriétés requises, TypeScript dira qu'elles correspondent, quels que soient les détails d'implémentation.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +TypeScript entretient une relation inhabituelle avec JavaScript. TypeScript offre toutes les fonctionnalités de JavaScript, et une couche supplémentaire en plus de celles-ci : le système de types de
```suggestion
TypeScript entretient une relation inhabituelle avec JavaScript. TypeScript offre toutes les fonctionnalités de JavaScript additionnées d'un surcouche : le système de types de TypeScript. Cela signifie que votre code fonctionnel JavaScript existant est également du code TypeScript.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +TypeScript est un langage qui est un sur-ensemble de JavaScript : la syntaxe JS est donc légale TS. TypeScript ne considère aucun code JavaScript comme une erreur en raison de sa *syntaxe*. Cela sign
```suggestion
TypeScript est un langage qui est un sur-ensemble de JavaScript : la syntaxe JS est donc du TS légal. TypeScript ne considère aucun code JavaScript comme en erreur en raison de sa *syntaxe*. Cela signifie que vous pouvez prendre n'importe quel code JavaScript fonctionnel et le mettre dans un fichier TypeScript sans vous soucier exactement de la façon dont il est écrit. Cependant, si vous déplacez du code d'un fichier JavaScript vers un fichier TypeScript, vous pourriez voir des erreurs de *type* selon la façon dont le code est écrit.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +TypeScript est un langage de programmation qui préserve le *comportement* d'exécution de JavaScript. Par exemple, la division par zéro en JavaScript produit « Infinity » au lieu de lever une exceptio
```suggestion
TypeScript est un langage de programmation qui préserve le *comportement* runtime de JavaScript. Par exemple, la division par zéro en JavaScript produit « Infinity » au lieu de lever une exception au runtime. Par principe, TypeScript **ne change jamais** le comportement runtime du code JavaScript et produira également `Infinity`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Garder le même comportement d'exécution que JavaScript est une promesse fondamentale de TypeScript, car cela signifie que vous pouvez facilement passer d'un langage à l'autre sans vous soucier des di
```suggestion
Garder le même comportement au runtime que JavaScript est une promesse fondamentale de TypeScript, car cela signifie que vous pouvez facilement passer d'un langage à l'autre sans vous soucier des différences subtiles qui pourraient empêcher votre programme de fonctionner.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +## Jouer autour
```suggestion
## Expérimeter
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Si vous voulez jouer avec TypeScript, vous pouvez soit l'installer localement `npm install -g typescript`, mettre votre code dans un fichier `.ts` et exécuter `tsc path/to/file.ts` pour le compiler,
```suggestion
Si vous voulez expérimenter avec TypeScript, vous pouvez soit l'installer localement `npm install -g typescript`, mettre votre code dans un fichier `.ts` et exécuter `tsc path/to/file.ts` pour le compiler, ou alors, essayer directement en ligne dans un [playground](https://www.typescriptlang.org/play?#code)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Cela signifie également que TypeScript ne modifie jamais le comportement de votre programme en fonction des types qu'il a déduits. L'essentiel est que même si vous pouvez voir des erreurs de type lor
```suggestion
Cela signifie également que TypeScript ne modifie jamais le comportement de votre programme en fonction des types qu'il a déduits. L'essentiel est que même si vous veniez à voir des erreurs de type lors de la compilation, le système de type n'a, en lui-même, aucune incidence sur le fonctionnement de votre programme lorsqu'il s'exécute.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Enfin, TypeScript ne fournit aucune bibliothèque d'exécution supplémentaire. Vos programmes utiliseront la même bibliothèque standard (ou bibliothèques externes) que les programmes JavaScript, il n'y
```suggestion
Enfin, TypeScript ne fournit aucune librairie runtime supplémentaire. Vos programmes utiliseront la même librairie standard (ou librairies externes) que les programmes JavaScript, il n'y a donc pas de framework supplémentaire spécifique à TypeScript à apprendre.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +### Primitives communes
```suggestion
### Primitives courantes
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +TypeScript n'utilise pas de déclarations de style « types à gauche » comme `int x = 0`. Les annotations de type iront toujours après la chose tapée.
```suggestion
TypeScript n'utilise pas le style de déclarations « types à gauche » comme `int x = 0`. Les annotations de type iront toujours après la chose typée.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les noms de type `String`, `Number` et `Boolean` (commençant par des lettres majuscules) sont légaux, mais font référence à certains types intégrés spéciaux qui apparaîtront très rarement dans votre
```suggestion
Les noms de type `String`, `Number` et `Boolean` (commençant par des lettres majuscules) sont légaux, mais font référence à certains types spéciaux intégrés  à TS qui apparaîtront très rarement dans votre code. *Toujours* utiliser `string`, `number` ou `boolean` pour les types.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +- `unknown` représente *toute* valeur. Ceci est similaire au type `any`, mais est plus sûr car il n'est pas légal de faire quoi que ce soit avec une valeur inconnue
```suggestion
- `unknown` représente *toute* valeur. Ceci est similaire au type `any`, mais est plus sûr car il n'est pas légal de faire quoi que ce soit avec une valeur de type unknown
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les énumérations sont une fonctionnalité ajoutée à JavaScript par TypeScript qui permet de décrire une valeur qui pourrait faire partie d'un ensemble de constantes nommées possibles. Contrairement à
```suggestion
Les énumérations sont une fonctionnalité ajoutée à JavaScript par TypeScript qui permet de décrire une valeur qui pourrait faire partie d'un ensemble de constantes nommées possibles. Contrairement à la plupart des fonctionnalités de TypeScript, il ne s'agit pas d'un ajout de typage à JavaScript, mais d'un élément ajouté au langage et à son exécution. Pour cette raison, il s'agit d'une fonctionnalité dont il est intéressant de connaître l'existence, mais que vous pouvez vous retenir d'utiliser à moins d'en être sûr. Vous pouvez en savoir plus sur les enums dans la [page de référence Enum](https://www.typescriptlang.org/docs/handbook/enums.html).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Certains programmeurs aiment utiliser `const` par défaut, puis passer à `let` si nécessaire. Cela permet d'avoir un code optimisé par défaut et évite de modifier les valeurs par erreur.
```suggestion
Certains programmeurs aiment utiliser `const` par défaut, puis passer à `let` si nécessaire. Cela permet d'avoir un code optimisé par défaut et évite de modifier des valeurs par erreur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les fonctions anonymes sont un peu différentes des déclarations de fonction. Lorsqu'une fonction apparaît à un endroit où TypeScript peut déterminer comment elle va être appelée, les paramètres de ce
```suggestion
Les fonctions anonymes sont un peu différentes des déclarations de fonction. Lorsqu'une fonction apparaît à un endroit où TypeScript peut déterminer comment elle va être appelée, les paramètres de cette fonction reçoivent automatiquement leurs types.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +En dehors des primitives, le type de type le plus courant que vous rencontrerez est un type d'objet. Cela fait référence à n'importe quelle valeur JavaScript avec des propriétés, c'est-à-dire presque
```suggestion
En dehors des primitives, le type le plus courant que vous rencontrerez est le type `objet`. Cela fait référence à n'importe quelle valeur JavaScript avec des propriétés, c'est-à-dire presque toutes ! Pour définir un type objet, on liste simplement ses propriétés et leurs types.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Pour éviter les répétitions, les types d'objets peuvent être nommés à l'aide d'une interface
```suggestion
Pour éviter les répétitions, les types d'objets peuvent être nommés à l'aide soit d'une interface
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +ou un alias de type.
```suggestion
soit d'un alias de type.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +## Traiter les valeurs nulles et non défini
```suggestion
## Traiter les valeurs null et undefined
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +À la base, le chaînage optionnel - l'opérateur `?` - nous permet d'écrire du code où TypeScript peut immédiatement arrêter l'exécution de certaines expressions si nous rencontrons un `null` ou `undef
```suggestion
L'optional chaining - l'opérateur `?` - nous permet d'écrire du code où TypeScript peut immédiatement arrêter l'exécution de certaines expressions si nous rencontrons un `null` ou `undefined`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +### Chaînage optionnel
Optional chaining

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +### Groupement nulle
C'est vraiment un concept qui a pas d'équivalent en français ^^"
```suggestion
### Nullish coalescing
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Vous pouvez considérer cette fonctionnalité - l'opérateur `??` - comme un moyen de « revenir » à une valeur par défaut lorsqu'il s'agit de `null` ou `undefined`.
```suggestion
Vous pouvez considérer cette fonctionnalité - l'opérateur `??` - comme un moyen de « repli »  vers une valeur par défaut lorsque `null` ou `undefined` sont rencontrées.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +`x`, `y` et `z` sont des déclarations de champs, ils créent des propriétés publiques en écriture sur la classe. Comme pour les autres emplacements, l'annotation de type est facultative, mais sera imp
```suggestion
`x`, `y` et `z` sont des déclarations de champs, ils créent des propriétés publiques en écriture sur la classe. Comme pour les autres emplacements, l'annotation de type est facultative, mais sera implicitement *any* si elle n'est pas spécifiée. Les champs peuvent avoir des *initiliseurs* comme `z`. Ceux-ci s'exécuteront automatiquement lorsque la classe sera instanciée. Tout comme avec `const`, `let` et `var`, l'initialiseur d'une propriété de classe sera utilisé pour déduire son type. Ici, cela signifie que, même s'il n'est pas explicitement écrit que `z` est de type `number`, le compilateur TypeScript le déduit du fait que `0` a été passé à `z`. Les champs peuvent être préfixés par le modificateur `readonly`. Cela empêche l'affectation du champ en dehors du constructeur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Une propriété de fonction sur une classe est appelée une méthode. Les méthodes peuvent utiliser toutes les annotations de même type que les fonctions et les constructeurs. Notez qu'à l'intérieur d'un
```suggestion
Une propriété fonction sur une classe est appelée une méthode. Les méthodes peuvent utiliser les mêmes annotations de type que les fonctions et les constructeurs. Notez qu'à l'intérieur d'un corps de méthode, il est toujours obligatoire d'accéder aux champs et autres méthodes via `this`. Un nom non qualifié dans un corps de méthode fera toujours référence à quelque chose dans le scope englobant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Comme d'autres aspects du système de types de TypeScript, `private` et `protected` ne sont appliqués que lors de la vérification de type. Cela signifie que les constructions d'exécution JavaScript ou
```suggestion
Comme d'autres aspects du système de types de TypeScript, `private` et `protected` ne sont appliqués que lors de la vérification de type. Cela signifie que les opérateurs JavaScript tels que `in` ou la simple recherche de propriété peuvent toujours accéder à un membre `private` ou `protected`. Si vous devez protéger les valeurs de votre classe contre les acteurs malveillants, vous devez utiliser des mécanismes offrant une confidentialité stricte à l'exécution, tels que des closures, des weak maps ou des champs private.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Depuis la version 3.8, Typescript prend en charge [les champs privés ECMAScript](https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields).
```suggestion
Depuis la version 3.8, Typescript prend en charge [les champs private ECMAScript](https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Comme d'autres langages dotés de fonctionnalités orientées objet, les classes en JavaScript peuvent hériter des classes de base.
```suggestion
Comme d'autres langages dotés de fonctionnalités orientées objet, les classes en JavaScript peuvent hériter de classes de base.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +- `extends`: Les classes peuvent s'étendre à partir d'une classe de base. Une classe dérivée possède toutes les propriétés et méthodes de sa classe de base et peut également définir des membres suppl
```suggestion
- `extends`: Les classes peuvent étendre une classe de base. Une classe dérivée possède toutes les propriétés et méthodes de sa classe de base et peut également définir des membres supplémentaires.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Dans TypeScript, tout comme dans ECMAScript 2015 (ES6), tout fichier contenant une importation ou une exportation de niveau supérieur est considéré comme un module.
```suggestion
En TypeScript, tout comme dans ECMAScript 2015 (ES6), tout fichier contenant à son début un import ou un export  est considéré comme un module.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +A l'inverse, un fichier sans aucune déclaration d'import ou d'export de niveau supérieur est traité comme un script dont le contenu est disponible dans la portée globale (et donc aussi pour les modul
```suggestion
A l'inverse, un fichier sans déclaration d'import ou d'export en début de fichier est traité comme un script dont le contenu est disponible dans le scope global (et donc aussi pour les modules).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +- Variables mutables déclarées à l'aide du mot-clé `let`. L'ancien mot-clé `var` peut également être utilisé mais n'est pas recommandé car sa façon de gérer la portée peut être trompeuse.
```suggestion
- Variables mutables déclarées à l'aide du mot-clé `let`. L'ancien mot-clé `var` peut également être utilisé mais n'est pas recommandé car sa façon de gérer le scope peut être trompeur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les modules sont exécutés dans leur propre portée, pas dans la portée globale. Cela signifie que les variables, fonctions, classes, etc. déclarées dans un module ne sont pas visibles en dehors du mod
```suggestion
Les modules sont exécutés dans leur propre scope, pas dans le scope global. Cela signifie que les variables, fonctions, classes, etc. déclarées dans un module ne sont pas visibles en dehors du module à moins qu'elles ne soient explicitement exportées à l'aide de l'une des syntaxes d'export. Inversement, pour consommer une variable, une fonction, une classe, une interface, etc. exportée d'un module différent, il faut l'importer à l'aide d'une des syntaxes d'import.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Comme dit précédemment, TypeScript est le langage principal d'Angular. La plupart des fonctionnalités de langage vues ci-dessus sont pleinement exploitées par Angular. Jetons un coup d'œil à un exemp
```suggestion
Comme dit précédemment, TypeScript est le langage principal d'Angular. La plupart des fonctionnalités du langage vues ci-dessus sont pleinement exploitées par Angular. Jetons un coup d'œil à un exemple simple d'un composant qui est l'un des principaux blocs de construction d'une application Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les principaux blocs de construction de Angular (services, composants, pipes, directives...) sont des classes. Le constructeur sert principalement à des fins d'injection de dépendance. Ici, nous voyo
```suggestion
Les principaux blocs de construction d'Angular (services, composants, pipes, directives...) sont des classes. Le constructeur sert principalement à des fins d'injection de dépendance. Ici, nous voyons une syntaxe où l'argument `service` est fourni avec un modificateur de visibilité, c'est une notation abrégée pour déclarer un champ sur une classe. Les deux exemples suivants sont strictement équivalents :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Decorators provide a way to add both annotations and a meta-programming syntax for class declarations and members. A Decorator is a special kind of declaration that can be attached to a class declara
```suggestion

```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les décorateurs permettent d'ajouter à la fois des annotations et une syntaxe de méta-programmation pour les déclarations de classe et les membres. Un décorateur est un type spécial de déclaration qu
```suggestion
Les décorateurs permettent d'ajouter à la fois des annotations et une syntaxe de méta-programmation pour les déclarations et les membres de classe. Un décorateur est un type spécial de déclaration qui peut être attaché à une déclaration de classe, une méthode, un accesseur, une propriété ou un paramètre. Les décorateurs utilisent la forme `@expression`, où `expression` doit être évalué en une fonction qui sera appelée au moment de l'exécution avec des informations sur la déclaration décorée. Angular utilise largement les décorateurs : `@Component`, `@Directive`, `@Injectable`, `@Pipe`, `@Input`, `@Output`...
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Les modules ES6 sont présents dans presque tous, sinon tous, les fichiers ts d'un projet Angular. Angular ajoute sa propre couche de module en plus de ceux-ci : NgModules. NgModules consolide les com
```suggestion
Les modules ES6 sont présents dans presque tous, sinon tous, les fichiers ts d'un projet Angular. Angular ajoute sa propre couche de module en plus de ceux-ci : les NgModules. Les NgModules consolident les composants, les directives et les pipes en blocs de fonctionnalités cohérents, chacun axé sur un groupe de fonctionnalités, un domaine business, un flux de travail ou une collection commune d'utilitaires. Nous en verrons plus à leur sujet plus tard dans la formation.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Les applications Angular, Angular CLI et Angular dépendent de [npm packages](https://docs.npmjs.com/about-npm) pour de nombreuses fonctionnalités et fonctions. Pour télécharger et installer des packa
```suggestion
Angular, le CLI Angular et les applications Angular dépendent de [packages npm](https://docs.npmjs.com/about-npm) pour de nombreuses fonctionnalités et fonctions. Pour télécharger et installer des packages npm, vous aurez besoin d'un gestionnaire de packages npm. Ce guide utilise l'interface en ligne de commande du [npm client](https://docs.npmjs.com/cli/v7/commands/npm-install), qui est installée avec Node.js par défaut.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Vous utilisez Angular CLI pour créer des projets, générer du code d'application et de bibliothèque et effectuer diverses tâches de développement en cours telles que les tests, le regroupement et le d
```suggestion
Vous utiliserez le CLI Angular pour créer des projets, générer du code dans vos applications et librairies et effectuer diverses tâches de développement telles que les tests, le bundling et le déploiement.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Pour installer Angular CLI, ouvrez une fenêtre de terminal et exécutez la commande suivante :
```suggestion
Pour installer le CLI Angular, ouvrez une fenêtre de terminal et exécutez la commande suivante :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +La commande `ng` est maintenant accessible depuis le terminal. Essayez-la pour vérifier l'installation et avoir plus d'informations sur les commandes disponibles. Vous pouvez également vérifier la [d
```suggestion
La commande `ng` est maintenant accessible depuis le terminal. Essayez-la pour vérifier l'installation et avoir plus d'informations sur les commandes disponibles. Vous pouvez également jeter un coup d’œil à la [documentation](https://angular.io/cli#command-overview).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Tout d'abord, installez le linter [TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin). Même s'il est maintenant obsolète, l'Angular CLI l'utilise t
```suggestion
Tout d'abord, installez le linter [TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin). Même s'il est maintenant déprécié, le CLI Angular l'utilise toujours par défaut.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +- Pour une installation plus légère, installez uniquement [Angular language service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template). Cette extension fournira, entre autres,
```suggestion
- Pour une installation plus légère, installez uniquement l'[Angular language service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template). Cette extension fournira, entre autres, l'autocomplétion.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +La première question influence les options des fichiers `tsconfig.json` et `angular.json`. Notamment, il définit l'indicateur `strict` sur true dans le fichier TSConfig, ce qui permet un large éventa
```suggestion
La première question influence les options des fichiers `tsconfig.json` et `angular.json`. Notamment, il définit le flag `strict` à true dans le fichier TSConfig, ce qui active un large éventail de fonctionnalités de vérification de type qui se traduisent par de meilleures garanties d'exactitude du programme. L'activer équivaut à activer toutes les options de la famille en mode strict : `strictBindCallApply`, `strictFunctionTypes`, `strictNullChecks` et `strictPropertyInitialization`. Il définit également sur true les trois `angularCompilerOptions` suivantes : `strictInjectionParameters`, `strictInputAccessModifiers` et `strictTemplates`. Ces options configurent le compilateur de template AOT (*Ahead-of-Time*).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +La deuxième question ajoute un fichier app-routing.module.ts qui importe le RouterModule. Dans Angular, la meilleure pratique consiste à charger et à configurer le routeur dans un module de niveau su
```suggestion
La deuxième question ajoute un fichier app-routing.module.ts qui importe le RouterModule. En Angular, une bonne pratique consiste à charger et à configurer le routeur dans un module distinct, dédié au routage et importé par le module root `AppModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +La dernière question vous fait choisir le format de la feuille de style. Ce format sera utilisé à deux endroits : pour le premier fichier `styles` et pour chaque composant généré. Le format SCSS vous
```suggestion
La dernière question vous fait choisir le format des feuilles de style. Ce format sera utilisé à deux endroits : pour le fichier global `styles` et pour chaque composant généré. Le format SCSS vous permet d'écrire du CSS standard et vous donne la possibilité de tirer parti de la puissance de Sass si vous choisissez de le faire.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Une fois que le projet a fini d'être généré, ouvrez le dossier du projet avec VS Code. (soit un clic droit sur le dossier soit via Fichier VSCode > Ouvrir le dossier...)
```suggestion
Une fois que le projet a fini d'être généré, ouvrez le dossier du projet avec VS Code. (soit un clic droit sur le dossier soit via VSCode: Fichier > Ouvrir le dossier...)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Votre application est accessible sur localhost:4200 (port par défaut si disponible). Il se recompilera automatiquement après chaque sauvegarde de fichier.
```suggestion
Votre application est accessible sur localhost:4200 (port par défaut si disponible). Elle se recompilera automatiquement après chaque sauvegarde de fichier.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/outillage/README.md
> +Les commandes de base en Angular CLI sont répertoriées dans le fichier README.md généré à la racine du projet
```suggestion
Les commandes de base du CLI Angular CLI répertoriées dans le fichier README.md généré à la racine du projet
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Nous venons d'utiliser la commande Angular CLI `ng new <my-project>`. Cette commande crée un espace de travail avec une application de niveau racine nommée *my-project* et installe les packages Angul
```suggestion
Nous venons d'utiliser la commande du CLI Angular `ng new <my-project>`. Cette commande crée un workspace nommé *my-project* avec une application dans le dossier src et installe les packages Angular npm nécessaires dans le nouveau workspace. Le dossier racine du workspace contient divers fichiers de support et de configuration.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +La création d'un squelette d'application initial au niveau racine de l'espace de travail avec ses tests de bout en bout est le comportement par défaut de la commande `ng new`. Ce comportement convien
```suggestion
La création initiale d'un squelette d'application à la racine du workspace avec ses tests de bout en bout est le comportement par défaut de la commande `ng new`. Ce comportement convient à un style de développement **multi-repo** où chaque application réside dans son propre workspace. C'est également la façon de faire recommandée pour les utilisateurs débutants et intermédiaires.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Pour commencer à développer avec un espace de travail multi-projets, la génération initiale de l'application au niveau racine doit être ignorée.
```suggestion
Pour commencer à développer avec un workspace multi-projets, la génération initiale de l'application à la racine doit être ignorée.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Angular prend également en charge les espaces de travail avec plusieurs projets. Ceci est approprié pour un style de développement **monorepo** où il y a un seul référentiel et une configuration glob
```suggestion
Angular prend également en charge les workspaces avec plusieurs projets. Ceci est approprié pour un style de développement **monorepo** où il y a un seul dépôt git et une configuration globale pour tous les projets Angular qu'il contient. Il convient également aux utilisateurs avancés qui, par exemple, développent des librairies à partager.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Vous pouvez ensuite générer des applications et des bibliothèques avec des noms uniques dans l'espace de travail.
```suggestion
Vous pouvez ensuite générer des applications et des librairies avec des noms uniques dans le workspace.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Les applications générées vont dans le dossier `projects/` au lieu d'un dossier `src` de niveau supérieur.
```suggestion
Les applications générées vont dans le dossier `projects/` au lieu d'un dossier `src` à la racine.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `tslint.json`: la configuration TSLint par défaut de l'espace de travail
```suggestion
- `tslint.json`: la configuration TSLint par défaut du workspace
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `tsconfig.json`: la configuration TypeScript de base pour les projets dans l'espace de travail
```suggestion
- `tsconfig.json`: la configuration TypeScript de base pour les projets dans le workspace
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `angular.json`: Configuration CLI, y compris les options de configuration pour les outils de génération, de service et de test utilisés par la CLI
```suggestion
- `angular.json`: Configuration du CLI, y compris des options de configuration pour les commandes build, serve et pour les outils de tests utilisés par le CLI
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `.gitignore`: Spécifie intentionnellement les fichiers non suivis que Git doit ignorer
```suggestion
- `.gitignore`: Spécifie les fichiers intentionnellement non suivis que Git doit ignorer
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `src`: Fichiers sources pour le projet d'application de niveau racine
```suggestion
- `src`: Fichiers sources pour l'application racine
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `node_modules`: Fournit des packages npm à l'ensemble de l'espace de travail
```suggestion
- `node_modules`: Fournit des packages npm à l'ensemble du workspace
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `e2e`: SFichiers sources pour un ensemble de tests de bout en bout qui correspondent à l'application de niveau racine, ainsi que des fichiers de configuration spécifiques aux tests
```suggestion
- `e2e`: Fichiers sources pour l'ensemble de tests de bout en bout de l'application racine, ainsi que des fichiers de configuration spécifiques aux tests
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Pour s'assurer que tous les développeurs travaillant sur un projet utilisent les mêmes versions de bibliothèque, il est possible de [bloquer les numéros de version](https://docs.npmjs.com/cli/v7/conf
```suggestion
Pour s'assurer que tous les développeurs travaillant sur un projet utilisent les mêmes versions de librairies, il est possible de [bloquer les numéros de version](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies) via le fichier `package.json`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `polyfill.ts`: Fournit des scripts polyfill pour la prise en charge du navigateur
```suggestion
- `polyfill.ts`: Fournit des scripts polyfill pour la prise en charge de navigateur
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `index.html`: a page HTML principale qui est diffusée lorsqu'un internaute visite votre site. La CLI ajoute automatiquement tous les fichiers JavaScript et CSS lors de la création de votre applicat
```suggestion
- `index.html`: La page HTML principale qui est diffusée lorsqu'un internaute visite votre site. Le CLI ajoute automatiquement tous les fichiers JavaScript et CSS lors de la création de votre application, vous n'avez donc généralement pas besoin d'ajouter manuellement de balises `<script>` ou `<link>` ici.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `assets`: Contient des images et d'autres fichiers d'actifs à copier tels quels lorsque vous créez votre application
```suggestion
- `assets`: Contient des images et d'autres fichiers d'assets à copier tels quels lors du build de votre application
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `app.module.ts`: Définit le module racine, nommé AppModule, qui indique à Angular comment assembler l'application. Déclare initialement uniquement le `AppComponent`. Au fur et à mesure que vous ajo
```suggestion
- `app.module.ts`: Définit le module racine, nommé AppModule, qui indique à Angular comment assembler l'application. Déclare initialement uniquement l'`AppComponent`. Au fur et à mesure que vous ajoutez d'autres composants à l'application, ils doivent être déclarés ici.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `app-routing.module.ts`: Définit un module de routage pour le `AppModule`
```suggestion
- `app-routing.module.ts`: Définit un module de routage pour l'`AppModule`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `app.component.html`: Définit le modèle HTML associé à la racine `AppComponent`
```suggestion
- `app.component.html`: Définit le template HTML associé au composant racine `AppComponent`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `app.component.scss`: Définit la feuille de style de base pour la racine `AppComponent`
```suggestion
- `app.component.scss`: Définit la feuille de style de base pour le composant racine `AppComponent`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `app.component.spec.ts`: Définit un test unitaire pour la racine `AppComponent`
```suggestion
- `app.component.spec.ts`: Définit un test unitaire pour le composant racine `AppComponent`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Ouvrez le fichier de classe de composant (`app.component.ts`) et modifiez la valeur de la propriété title en 'Search films'
```suggestion
Ouvrez le fichier de classe du composant (`app.component.ts`) et modifiez la valeur de la propriété title en 'Search films'
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Ouvrez le fichier de modèle de composant (`app.component.html`) et supprimez le modèle par défaut généré par Angular CLI. Remplacez-le par la ligne HTML suivante.
```suggestion
Ouvrez le fichier de template du composant (`app.component.html`) et supprimez le modèle par défaut généré par le CLI Angular. Remplacez-le par la ligne d'HTML suivante.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Les accolades doubles sont la *syntaxe de liaison d'interpolation* d'Angular. Cette liaison d'interpolation présente la valeur de la propriété title du composant à l'intérieur de la balise d'en-tête
```suggestion
Les doubles accolades sont la *syntaxe d'interpolation binding* d'Angular. Cet interpolation binding présente la valeur de la propriété title du composant à l'intérieur de la balise h1.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- affectations (`=`, `+=`, ...)
```suggestion
- les affectations (`=`, `+=`, ...)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- opérateurs tels que `new`, `typeof` ou `instanceof`
```suggestion
- les opérateurs tels que `new`, `typeof` ou `instanceof`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Dans cet exemple, nous avons formaté le prix manuellement. Nous verrons plus tard que Angular fournit un moyen de déclarer des formateurs réutilisables : **pipes**.
```suggestion
Dans cet exemple, nous avons formaté le prix manuellement. Nous verrons plus tard qu'Angular fournit un moyen de déclarer des formateurs réutilisables : les **pipes**.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Le `AppComponent` n'est que le composant racine d'une application Angular. Une application Web est constituée de petits composants réutilisables, intégrés dans des composants de niveau supérieur pour
```suggestion
L'`AppComponent` n'est que le composant racine d'une application Angular. Une application Web est constituée de petits composants réutilisables, intégrés dans des composants de niveau supérieur pour former la mise en page, la disposition de vos éléments sur la page. Cette structure peut être décrite comme une arborescence de composants. Angular crée, met à jour et détruit les composants au fur et à mesure que l'utilisateur se déplace dans l'application. L'application peut agir à chaque instant de ce cycle de vie via des hooks de cycle de vie facultatifs, comme `ngOnInit()`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Créons un second composant. Il est conseillé de générer des composants en utilisant [Angular CLI](https://angular.io/cli/generate#component).
```suggestion
Créons un second composant. Il est conseillé de générer les composants en utilisant le [CLI Angular](https://angular.io/cli/generate#component).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +La commande `ng g c` a ajouté un dossier `child` contenant les fichiers `ChildComponent` dans le dossier `app`.
```suggestion
La commande `ng g c` a ajouté un dossier `child` contenant les fichiers du composant `ChildComponent` dans le dossier `app`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Pour lier les composants entre eux, les composants enfants sont déclarés dans le modèle de composant de leur parent, en utilisant leur sélecteur comme balise. Un composant peut être réutilisé autant
```suggestion
Pour lier les composants entre eux, les composants enfants sont déclarés dans le template de leur composant parent, en utilisant leur sélecteur comme balise. Un composant peut être réutilisé autant de fois que souhaité. Le sélecteur de `ChildComponent` est `app-child`. L'inclusion de ce composant en tant qu'enfant de l'`AppComponent` se fait comme suit :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Angular préfixe automatiquement les sélecteurs afin que les composants importés de bibliothèques externes soient plus faciles à repérer. Par exemple, les composants de la bibliothèque Material Angula
```suggestion
Angular préfixe automatiquement les sélecteurs afin que les composants importés de librairies externes soient plus faciles à repérer. Par exemple, les composants de la librairie Material Angular sont tous préfixés par `mat-`. Vous pouvez modifier le préfixe de l'application dans le fichier de configuration « angular.json » afin qu'il reflète le nom de votre application.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +En coulisse, la commande `ng g c` a également déclaré le composant `Child` dans `AppModule`.
```suggestion
En coulisse, la commande `ng g c` a également déclaré le composant `Child` dans l'`AppModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `exports`: Le sous-ensemble de déclarations qui doit être visible et utilisable dans les modèles de composants d'autres NgModules. (le `AppModule` n'a aucune raison d'exporter quoi que ce soit car
```suggestion
- `exports`: Le sous-ensemble de déclarations qui doit être visible et utilisable dans les templates des composants d'autres NgModules. (l'`AppModule` n'a aucune raison d'exporter quoi que ce soit car les autres modules n'ont pas besoin d'importer le NgModule racine)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `imports`: D'autres modules dont les classes exportées sont nécessaires aux modèles de composants déclarés dans ce NgModule.
```suggestion
- `imports`: D'autres modules dont les classes exportées sont nécessaires aux template des composants déclarés dans ce NgModule.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +- `providers`: Créateurs de services que ce NgModule contribue à la collection globale de services ; ils deviennent accessibles dans toutes les parties de l'application. (Vous pouvez également spécif
```suggestion
- `providers`: Créateurs de services que ce NgModule contribue à la collection globale de services ; ils deviennent accessibles dans toutes les parties de l'application. (Vous pouvez également spécifier des providers au niveau du composant.)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Bien qu'une petite application puisse n'avoir qu'un seul NgModule, au fur et à mesure que l'application grandit, il est recommandé de refactoriser le module racine en modules de fonctionnalités qui r
```suggestion
Bien qu'une petite application puisse n'avoir qu'un seul NgModule, au fur et à mesure que l'application grandit, il est recommandé de refactoriser le module racine en modules de fonctionnalités qui représentent des collections de fonctionnalités connexes. Vous pouvez ensuite soit importer ces modules dans le module racine (eagerly loaded) ou les charger de manière asynchrone via le routeur (lazily loaded).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Cette structure de dossiers est la mieux adaptée aux projets simples qui n'ont qu'un seul module, le `AppModule`. Au fur et à mesure qu'un projet grandit, des modules de fonctionnalités seront introd
```suggestion
Cette structure de dossiers est la mieux adaptée aux projets simples qui n'ont qu'un seul module, l'`AppModule`. Au fur et à mesure qu'un projet grandit, des modules de fonctionnalités seront introduits et la structure peut évoluer vers ceci :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +Par défaut, la CLI sera toujours générée dans le dossier `app`. Vous pouvez lui dire de générer dans un autre dossier en passant le chemin avant le nom de l'élément que vous souhaitez qu'il génère. P
```suggestion
Par défaut, le CLI toujours générera toujours dans le dossier `app`. Vous pouvez lui dire de générer dans un autre dossier en passant le chemin avant le nom de l'élément que vous souhaitez qu'il génère. Par exemple, `ng generate component components/test` générera les quatre fichiers du composant `TestComponent` dans `app/components/test`. Le dossier `components` est créé par le CLI s'il n'existait pas déjà, ainsi que le dossier `test`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +1. La plupart des applications s'efforcent d'avoir une apparence cohérente sur l'ensemble de l'application. La CLI a généré un `styles.scss` vide à cet effet. Copiez coller le contenu de la feuille d
```suggestion
1. La plupart des applications s'efforcent d'avoir une apparence cohérente sur l'ensemble de l'application. Le CLI a généré un `styles.scss` vide à cet effet. Copiez coller dedans le contenu de la feuille de style SCSS qui servira de base à tous les travaux pratiques, téléchargeable ici : [styles.scss](https://worldline.github.io/angular-training/styles.scss).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +3. Supprimez le contenu existant du modèle `AppComponent` et affichez le `LoginFormComponent` à la place avec `<app-login-form></app-login-form>`. Vérifiez que la CLI a ajouté le `LoginFormComponent`
```suggestion
3. Supprimez le contenu existant du template de composant `AppComponent` et affichez le `LoginFormComponent` à la place avec `<app-login-form></app-login-form>`. Vérifiez que le CLI a ajouté le `LoginFormComponent` à la liste de `déclarations` dans l'`AppModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/premiers-pas/README.md
> +4. Complétez le fichier `login-form.component.ts` : ajoutez un champ contenant une propriété de titre. Ensuite, utilisez l'interpolation de texte dans le modèle pour passer le titre du formulaire à l
```suggestion
4. Complétez le fichier `login-form.component.ts` : ajoutez un champ contenant une propriété title. Ensuite, utilisez l'interpolation binding dans le template pour passer le titre du formulaire à la balise h1.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +# Renforcez votre HTML
```suggestion
# Dynamisez votre HTML
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +Angular apporte une syntaxe puissante aux templates. Dans le chapitre précédent, nous avons vu l'interpolation de texte `{{}}`. Dans ce chapitre, nous aborderons quelques éléments de ce système de sy
```suggestion
Angular apporte une syntaxe puissante aux templates. Dans le chapitre précédent, nous avons vu l'interpolation de texte `{{}}`. Dans ce chapitre, nous aborderons quelques éléments de ce système de syntaxe : le property binding, l'event binding, le class et style binding, les directives d'attribut et les directives structurelles.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +## Liaison de propriété
```suggestion
## Property binding
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +Pour lier un élément HTML à la propriété d'un composant, placez-le entre crochets `[]`. Les crochets, `[]`, obligent Angular à évaluer le côté droit de l'affectation en tant qu'expression dynamique.
```suggestion
Pour lier un élément HTML à la propriété d'un composant, placez-le entre crochets `[]`. Les crochets, `[]`, obligent Angular à évaluer le côté droit de l'affectation en tant qu'expression dynamique. Sans les crochets, Angular traite le côté droit comme un littéral  et donne pour valeur à la propriété cette valeur statique. `[]` est la syntaxe pour le one-way data binding avec les données circulant du composant vers le template.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +## Liaison de classe et de style
```suggestion
## Class et style binding
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +### Liaison de classe
```suggestion
### Class binding
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +Vous pouvez utiliser la liaison de classe pour ajouter et supprimer des noms de classe CSS de l'attribut `class` d'un élément. Pour créer une liaison de classe unique, utilisez le préfixe `class` sui
```suggestion
Vous pouvez utiliser le class binding pour ajouter et supprimer des noms de classe CSS à l'attribut `class` d'un élément. Pour créer un class binding pour une seule classe, utilisez le préfixe `class` suivi d'un point et du nom de la classe CSS, par exemple, `[class.sale]="onSale"`. Angular ajoute la classe lorsque l'expression liée, `onSale` est vraie, et supprime la classe lorsque l'expression est fausse.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +### Liaison de style
```suggestion
### Style binding
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +Vous pouvez utiliser la liaison de style pour définir des styles de manière dynamique. Pour créer une liaison de style unique, utilisez le préfixe `style` suivi d'un point et du nom de la propriété d
```suggestion
Vous pouvez utiliser le style binding pour définir des styles de manière dynamique. Pour créer un style binding pour une seule propriété de style CSS, utilisez le préfixe `style` suivi d'un point et du nom de la propriété de style CSS, par exemple, [style.width]="width" avec `width = "100px"` (width est un chaîne de caractères). En option, vous pouvez ajouter une extension d'unité comme `em` ou `%` : [style.width.px]="width" avec `width = 100` (width est un nombre).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +Alternativement, vous pouvez basculer les styles et les classes via deux directives :
```suggestion
Alternativement, vous pouvez dynamiquement activer les styles et les classes via deux directives :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +L'utilisation de la syntaxe de liaison de style sans NgStyle est préférable. En raison des améliorations, `NgStyle` ne fournit plus de valeur significative par rapport à `[style]` et pourrait éventue
```suggestion
L'utilisation de la syntaxe de style binding sans NgStyle est préférable. En raison des améliorations, `NgStyle` ne fournit plus de valeur significative par rapport à `[style]` et pourrait éventuellement être supprimé d'Angular à l'avenir.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +**Exercise: attribuer une classe et une couleur à chaque fantôme en utilisant la classe**
```suggestion
**Exercise: attribuer une classe et une couleur à chaque fantôme en utilisant class, style, ngClass ou ngStyle**
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +La directive NgModel vous permet de lier la valeur d'un champ de formulaire à un élément de données de composant. Il s'agit d'une liaison bidirectionnelle : la variable est mise à jour lorsque le con
```suggestion
La directive NgModel vous permet de lier la valeur d'un champ de formulaire à une propriété du composant. Il s'agit d'une liaison bidirectionnelle : la propriété est mise à jour lorsque le contenu du champ change (typiquement par l'utilisateur) et vice versa. La syntaxe pour la liaison de données bidirectionnelle est `[()]`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +La directive `NgModel` ne fait pas partie des importations par défaut d'un `NgModule`. Vous devez l'ajouter vous-même : ajoutez `FormsModule` à la liste des importations de `AppModule`.
```suggestion
La directive `NgModel` ne fait pas partie des imports par défaut d'un `NgModule`. Vous devez l'ajouter vous-même : ajoutez `FormsModule` à la liste d'imports de l'`AppModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +**Exercise: use an NgIf to toggle the loader**
```suggestion
**Exercice: utilisez un NgIf pour montrer/cacher le loader**
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +**Bonus: use an NgIf Else to conditionnally show either the data or the no data message**
```suggestion
**Bonus: utilisez un NgIf Else pour conditionnellement montrer soir les données soit le message comme quoi les données ne sont pas disponibles**
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +`NgSwitch` échange conditionnellement le contenu de l'élément hôte en sélectionnant l'un des modèles intégrés en fonction de la valeur actuelle de conditionExpression.
Faudra que je corrige la partie en anglais
```suggestion
`NgSwitch` échange conditionnellement le contenu de l'élément hôte en sélectionnant l'un des template enfants en fonction de la valeur actuelle de l'expression.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +`*ngIf` et `*ngFor` ne peuvent pas être placés en même temps sur un élément HTML. Pour répéter un bloc de HTML lorsqu'une condition particulière est vraie, soit un niveau supplémentaire de HTML doit
```suggestion
`*ngIf` et `*ngFor` ne peuvent pas être placés en même temps sur un élément HTML. Pour répéter un bloc d'HTML lorsqu'une condition particulière est vraie, soit un niveau supplémentaire d'HTML doit être introduit, ce qui n'est pas toujours souhaitable et peut casser le style, soit la balise `<ng-container>` fournie par Angular peut être utilisée . `<ng-container>` n'est pas présent dans le DOM.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +## Liaison d'événement
```suggestion
## Event binding
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +La liaison d'événements vous permet d'écouter et de répondre aux actions de l'utilisateur telles que les frappes, les mouvements de souris, les clics et les touches ou un événement personnalisé émis
```suggestion
L'event binding permet d'écouter et de répondre aux actions de l'utilisateur telles que les frappes, les mouvements de souris, les clics et les touchers ou un événement custom émis par un composant enfant. Pour lier le composant à un événement, utilisez la syntaxe d'event binding d'Angular `()`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +- Directives d'attributs qui modifient l'apparence ou le comportement d'un élément
```suggestion
- Les directives d'attributs qui modifient l'apparence ou le comportement d'un élément
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +2. Ajoutez un autre champ « loggedIn » initialement défini sur « false », puis utilisez la liaison d'événement avec « (ngSubmit) » sur la balise du formulaire pour le définir sur « true » lorsque le
```suggestion
2. Ajoutez un autre champ `loggedIn` initialement défini à `false`, puis utilisez l'event binding avec `(ngSubmit)` sur la balise `form` pour le passer à `true` lorsque le formulaire est soumis.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +4. Utilisez la directive `*ngIf` et la liaison de template `else` pour afficher le formulaire d'authentification et masquer la liste des films lorsque `loggedIn === false`, et vice versa.
```suggestion
4. Utilisez la directive `*ngIf else` pour afficher le formulaire d'authentification et masquer la liste des films lorsque `loggedIn === false`, et vice versa.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +7. Complétez la carte avec les données de chaque film en utilisant la liaison des propriétés et l'interpolation.
```suggestion
7. Complétez la carte avec les données de chaque film en utilisant le property binding et l'interpolation.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Les pipes sont des **fonctions de transformation de données** utilisables directement depuis le template afin de transformer les données à afficher au moment de la liaison. Ils sont intéressants de d
```suggestion
Les pipes sont des **fonctions de transformation de données** utilisables directement depuis le template afin de transformer les données à afficher au moment du binding. Ils sont intéressants de deux manières principales :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- ils ne nécessitent pas de modifier les données dans le composant pour qu'il s'affiche de manière conviviale
```suggestion
- ils ne nécessitent pas de modifier les données dans le composant pour qu'elles s'affichent de manière user-friendly
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +La syntaxe des pipe de Angular pipe syntax est inspirée de celle de shell Unix
```suggestion
La syntaxe des pipes Angular est inspirée de celle du shell Unix
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Les paramètres peuvent être passés aux pipes. Ils sont placés après le nom du pipe et séparés par des deux-points :
```suggestion
Des paramètres peuvent être passés aux pipes. Ils sont placés après le nom du pipe et séparés par des deux-points :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Angular fournit plus d'une [douzaine de pipes intégrés](https://angular.io/api?type=pipe) pour couvrir les cas d'utilisation courants. Voici une liste complète d'entre eux :
```suggestion
Angular fournit plus d'une [douzaine de pipes intégrés](https://angular.io/api?type=pipe) pour couvrir les cas d'utilisation courants. Voici leur liste complète :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `CurrencyPipe` transforme un nombre en une chaîne de devise selon les règles locales
```suggestion
- `CurrencyPipe` transforme un nombre en une chaîne de caractère formatée avec la devise selon les règles de locale
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `DatePipe` formate une valeur de date selon les règles locales
```suggestion
- `DatePipe` formate une valeur de date selon les règles de locale
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `DecimalPipe` formate une valeur en fonction des options numériques et des règles locales
```suggestion
- `DecimalPipe` formate une valeur en fonction d'option de formatage des décimales et des règles de locale
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `I18nPluralPipe` fait correspondre une valeur à une chaîne qui pluralise la valeur selon les règles locales
```suggestion
- `I18nPluralPipe` fait correspondre une valeur à une chaîne de caractère qui pluralise la valeur selon les règles de locale
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `I18nSelectPipe` sélecteur générique qui affiche la chaîne qui correspond à la valeur actuelle
```suggestion
- `I18nSelectPipe` sélecteur générique qui affiche la chaîne de caractère qui correspond à la valeur actuelle
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `KeyValuePipe` transforme l'objet ou la carte en un tableau de paires clé-valeur
```suggestion
- `KeyValuePipe` transforme l'objet ou la Map en un tableau de paires clé-valeur
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `PercentPipe` transforme un nombre en une chaîne de pourcentage, formatée selon les règles locales
```suggestion
- `PercentPipe` transforme un nombre en une chaîne de caractères formatée avec en pourcentage, selon les règles de locale
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- `SlicePipe` crée un nouveau tableau ou chaîne contenant un sous-ensemble (tranche) des éléments
```suggestion
- `SlicePipe` crée un nouveau tableau ou chaîne de caractère contenant un sous-ensemble (tranche) des éléments
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +- décorez-le avec le décorateur `@Pipe()`
```suggestion
- décorez-la avec le décorateur `@Pipe()`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +La CLI s'occupera de ces trois points pour nous via la [commande suivante](https://angular.io/cli/generate#pipe):
```suggestion
Le CLI s'occupera de ces trois points pour nous via la [commande suivante](https://angular.io/cli/generate#pipe):
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Le premier argument de la méthode `transform` est la valeur sur laquelle le pipe est appliqué, la méthode prend alors n'importe quel nombre d'arguments. Il est recommandé de saisir tous les arguments
```suggestion
Le premier argument de la méthode `transform` est la valeur sur laquelle le pipe est appliqué, la méthode prend ensuite n'importe quel nombre d'arguments. Il est recommandé de typer tous les arguments ainsi que de préciser le type de retour.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Le nom du pipe doit être en minusculeCamelCase. C'est une bonne pratique de le faire commencer par les initiales de votre application, tout comme pour le sélecteur de vos composants.
```suggestion
Le nom du pipe doit être en lowerCamelCase. C'est une bonne pratique de le faire commencer par les initiales de votre application, tout comme pour le sélecteur de vos composants.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Comme toute autre classe, les pipes peuvent utiliser leur constructeur pour bénéficier de l'injection de dépendances. Il est possible d'injecter un autre pipe par exemple. Ceci est particulièrement u
```suggestion
Comme toute autre classe, les pipes peuvent utiliser leur constructeur pour bénéficier de l'injection de dépendances. Il est possible d'injecter un autre pipe par exemple. Ceci est particulièrement utile lorsqu'un pipe intégré doit être utilisé dans toute l'application avec les mêmes paramètres. Un pipe personnalisé peut servir de wrapper afin de simplifier l'utilisation d'un pipe intégré.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Dans l'exemple suivant, le prix remisé est calculé en fonction d'un taux de remise. Aucune donnée de catalogue dans le composant n'est mutée pour afficher le nouveau prix.
```suggestion
Dans l'exemple suivant, le prix remisé est calculé en fonction d'un taux de remise. Aucune donnée du catalogue dans le composant n'est mutée pour afficher le nouveau prix.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +Il est également possible d'utiliser des pipes dans une classe de composant en l'injectant dans son constructeur et en appelant sa méthode transform. Le pipe doit être importé dans le module auquel a
```suggestion
Il est également possible d'utiliser des pipes dans une classe de composant en l'injectant dans son constructeur et en appelant sa méthode transform. Le pipe doit être importé dans le module auquel appartient le composant et ajouté aux providers du composant ou du module (à privilégier).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +1. Créez un pipe `starRating` à l'aide de CLI dans `app/pipes`.
```suggestion
1. Créez un pipe `starRating` à l'aide du CLI dans `app/pipes`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pipes/README.md
> +2. Implémentez l'intérieur des méthodes de transformation de sorte que le métascore d'un film s'affiche avec une note de ★ à cinq ★★★★★.
```suggestion
2. Implémentez l'intérieur de la méthode transform de sorte que le métascore d'un film s'affiche avec une note de ★ à cinq ★★★★★.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ViewEncapsulation.Native` : Angular crée un Shadow DOM pour le composant, les styles sont limités au composant
```suggestion
- `ViewEncapsulation.ShadowDom` : Angular crée un Shadow DOM pour le composant, les styles sont limités au composant
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ViewEncapsulation.Emulated` (par défaut) : émule le Shadow DOM, les styles sont limités au composant
```suggestion
- `ViewEncapsulation.Emulated` (par défaut) : émule le scoping natif,, les styles sont limités au composant
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Sous l'option par défaut, les styles spécifiés dans le fichier de style du composant ne sont hérités par aucun composant imbriqué dans le template ni par aucun contenu projeté dans le composant.
```suggestion
Sous l'option par défaut, les styles spécifiés dans le fichier de style du composant ne sont hérités par aucun composant imbriqué dans son template ni par aucun contenu projeté dans le composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +### `:host` selector
```suggestion
### Sélecteur CSS `:host`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Des situations peuvent survenir où le style de l'élément hôte du composant à partir de la feuille de style du composant est nécessaire. Pour ce faire, Angular fournit un sélecteur de pseudo-classe :
```suggestion
Des situations peuvent survenir où styler l'élément hôte du composant à partir de sa propre feuille de style est nécessaire. Pour ce faire, Angular fournit un sélecteur de pseudo-classe : `:host`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +<code-block title="app.component.ts">
```suggestion
<code-block title="app.component.scss">
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +<code-block title="app.component.ts">
```suggestion
<code-block title="app.component.scss">
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Une instance de composant a un cycle de vie qui commence lorsque Angular instancie la classe de composant et restitue la vue du composant avec ses vues enfants. Le cycle de vie se poursuit avec la dé
```suggestion
Une instance de composant a un cycle de vie qui commence lorsqu'Angular instancie la classe du composant et présente la vue du composant avec ses vues enfants. Le cycle de vie se poursuit avec la détection des modifications, car Angular vérifie quand les propriétés liées aux données changent et met à jour à la fois la vue et l'instance de composant si nécessaire. Le cycle de vie se termine lorsqu'Angular détruit l'instance du composant et retire son template du DOM.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Angular fournit des méthodes de hook de cycle de vie pour exploiter les événements clés du cycle de vie d'un composant.
```suggestion
Angular fournit des méthodes de hook pour exploiter les événements clés du cycle de vie d'un composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngOnChanges`: appelé après le constructeur et chaque fois que les valeurs d'entrée changent. La méthode reçoit un objet SimpleChanges des valeurs de propriété actuelles et précédentes.
input fait référence aux propriétés de la classe du composant annotées d'@Input()
```suggestion
- `ngOnChanges`: appelée après le constructeur et chaque fois que les valeurs input changent. La méthode reçoit un objet SimpleChanges qui contient les valeurs actuelles et précédentes des propriétés annotées d'@Input().
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngOnInit`: appelé une seule fois. C'est là que l'**initialisation du composant** doit avoir lieu, comme **la récupération des données initiales**. En effet, les composants doivent être peu coûteux
```suggestion
- `ngOnInit`: appelée une seule fois. C'est là que l'**initialisation du composant** doit avoir lieu, tel que **la récupération des données initiales**. En effet, les composants doivent être peu coûteux à construire, les opérations coûteuses doivent donc être tenues à l'écart du constructeur. Le constructeur ne doit pas faire plus que donner des valeurs initiales simples aux variables de la classe.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngDoCheck`: appelé immédiatement après `ngOnChanges` à chaque exécution de détection de changement, et immédiatement après `ngOnInit` lors de la première exécution. Donne la possibilité de mettre
```suggestion
- `ngDoCheck`: appelée immédiatement après `ngOnChanges` à chaque exécution du cycle de détection du changement, et immédiatement après `ngOnInit` lors de la première exécution. Donne la possibilité de mettre en œuvre un algorithme de détection du changement personnalisé.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngAfterContentInit`: appelé une seule fois. Invoqué après que Angular ait effectué une projection de contenu dans la vue du composant.
```suggestion
- `ngAfterContentInit`: appelée une seule fois. Invoquée après qu'Angular ait effectué une projection de contenu dans la vue du composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngAfterContentChecked`: appelé après `ngAfterContentInit` et chaque `ngDoCheck` suivant.
```suggestion
- `ngAfterContentChecked`: appelée après `ngAfterContentInit` et chaque `ngDoCheck` suivant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngAfterViewInit`: appelé une seule fois. Appelé lorsque la vue du composant a été complètement initialisée.
```suggestion
- `ngAfterViewInit`: appelée une seule fois. Appelée lorsque la vue du composant a été complètement initialisée.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +- `ngAfterViewChecked`: appelé après `ngAfterViewInit` et chaque `ngDoCheck` suivant.
```suggestion
- `ngAfterViewChecked`: appelée après `ngAfterViewInit` et chaque `ngDoCheck` suivant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +For each lifecycle hook there exists a corresponding interface. Their name is derived from the lifecycle hook's they define minus the `ng`. For instance, to use `ngOnInit()` implement the interface `
```suggestion
Pour chaque hook du cycle de vie il existe une interface correspondante. Leurs noms sont dérivés du nom du hook de cycle de vie correspondant moins le `ng`. Par exemple, pour utiliser `ngOnInit()`, implémentez l'interface `OnInit`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Un modèle courant dans Angular est le partage de données entre un composant parent et un ou plusieurs composants enfants. Vous pouvez implémenter ce modèle en utilisant les directives `@Input()` et `
```suggestion
Une pratique courante dans Angular est le partage de données entre un composant parent et un ou plusieurs composants enfants. Pour ce faire, vous pouvez utiliser les directives `@Input()` et `@Output()`. `@Input()` permet à un composant parent de mettre à jour les données dans le composant enfant. Inversement, `@Output()` permet à l'enfant d'envoyer des données à un composant parent.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +L'ajout du décorateur `@Input()` sur la propriété d'un composant enfant signifie qu'il peut recevoir sa valeur de son composant parent. Le composant parent transmet cette valeur via la liaison de pro
```suggestion
L'ajout du décorateur `@Input()` sur une propriété d'un composant enfant signifie qu'il peut recevoir sa valeur de son composant parent. Le composant parent transmet cette valeur via property binding dans son template. Une telle propriété **ne devrait pas être mutée par l'enfant** directement. Les mutations doivent se produire dans le parent, elles se propageront automatiquement via le property binding.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Voici comment le `AppComponent` communiquerait à son composant enfant `BlogPostComponent` le titre et le contenu de son article.
```suggestion
Voici comment l'`AppComponent` communiquerait à son composant enfant `BlogPostComponent` le titre et le contenu de son article.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +L'ajout du décorateur `@Output()` sur la propriété `EventEmitter` d'un composant enfant permet aux données de circuler de l'enfant vers le parent. Le composant parent peut réagir à l'événement via la
```suggestion
L'ajout du décorateur `@Output()` sur une propriété de type `EventEmitter` d'un composant enfant permet aux données de circuler de l'enfant vers le parent. Le composant parent peut réagir à l'événement via la syntaxe d'event binding.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Vous pouvez essayer avec cette exemple [ici](https://stackblitz.com/edit/angular-output-training-example?file=src/app/app.component.ts).
```suggestion
Vous pouvez expérimenter avec cet exemple [ici](https://stackblitz.com/edit/angular-output-training-example?file=src/app/app.component.ts).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Un composant parent ne peut pas utiliser la liaison de données (`@Output` ou `@Input`) pour accéder aux propriétés ou méthodes d'un enfant. Une variable locale dans le template peut être utilisée pou
```suggestion
Un composant parent ne peut pas utiliser le data binding (`@Output` ou `@Input`) pour accéder aux propriétés ou méthodes d'un enfant. Une variable locale dans le template peut être utilisée pour réaliser les deux.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Le décorateur `ViewChild` peut atteindre le même objectif qu'une variable de template mais directement à l'intérieur de la classe du composant parent en injectant le composant enfant dans le composan
```suggestion
Le décorateur `ViewChild` peut accomplir le même objectif qu'une variable de template mais directement à l'intérieur de la classe du composant parent en injectant le composant enfant dans le composant parent. Utilisez `ViewChild` sur une variable locale chaque fois que vous devez coordonner les interactions entre plusieurs composants enfants.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Dans le cas où le composant parent contient plusieurs instances du même composant enfant, elles peuvent chacune être interrogées via la variable de référence du template :
```suggestion
Dans le cas où le composant parent contient plusieurs instances du même composant enfant, elles peuvent chacune être récupérées via une variable de référence du template :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +Les composants injectés via `@ViewChild` deviennent disponibles dans le hook de cycle de vie `ngAfterViewInit`. Pour interroger tous les enfants d'un certain type, utilisez le décorateur `@ViewChildr
```suggestion
Les composants injectés via `@ViewChild` deviennent disponibles dans le hook de cycle de vie `ngAfterViewInit`. Pour récupérer tous les enfants d'un certain type, utilisez le décorateur `@ViewChildren`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +1. Refactorisez le `LoginFormComponent` pour extraire le code et le template liés aux détails d'un film. Pour cela, créez avec CLI un `FilmComponent`, il y aura autant d'instances de `FilmComponent`
```suggestion
1. Refactorisez le `LoginFormComponent` pour extraire le code et le template liés aux détails d'un film. Pour cela, créez avec le CLI un `FilmComponent`, il y aura autant d'instances de `FilmComponent` qu'il y a de films. Utilisez `@Input()` pour transmettre les données du `LoginFormComponent` à chaque `FilmComponent`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +2. Créez un autre composant avec CLI : `FilmSearchComponent`. Il contiendra un formulaire de recherche et la liste `FilmComponent` ci-dessous :
```suggestion
2. Créez un autre composant avec le CLI : `FilmSearchComponent`. Il contiendra un formulaire de recherche et la liste de `FilmComponent` ci-dessous :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/composants/README.md
> +4. Affichez le composant `FilmSearchComponent` uniquement si l'utilisateur est connecté. Vous devrez communiquer la variable `loggedIn` du `LoginFormComponent` au `AppComponent` via un `@Output()`.
```suggestion
4. Affichez le composant `FilmSearchComponent` uniquement si l'utilisateur est connecté. Vous devrez communiquer la variable `loggedIn` du `LoginFormComponent` à l'`AppComponent` via un `@Output()`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Les applications Angular sont principalement des applications à page unique (SPA). Le serveur sert toujours une seule page HTML, et la navigation entre les pages/sections de l'application est gérée c
```suggestion
Les applications Angular sont principalement des SPA (Single Page Application). Le serveur sert toujours une seule page HTML, et la navigation entre les pages/sections de l'application est gérée côté client en JavaScript. Cette approche permet des transitions plus fluides entre les pages et réduit le nombre d'appels au serveur nécessaires pour naviguer entre les pages, améliorant ainsi l'UX. Ceci est essentiel pour les applications Progressive Web Apps ou les applications Web qui souhaitent disposer de fonctionnalités hors ligne.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le routage d'un SPA est donc géré côté client, et l'équipe Angular met à disposition une librairie à cet effet : `@angular/router`. Ce routeur vous permet d'associer des routes (URL) avec des composa
```suggestion
Le routage d'une SPA est donc géré côté client, et l'équipe Angular met à disposition une librairie à cet effet : `@angular/router`. Ce routeur vous permet d'associer des routes (URL) avec des composants Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Pour ce chapitre, nous utiliserons l'application *Bibliothèque personnelle* comme exemple d'exécution. Outre le `AppComponent` qui contient un `NavbarComponent`, l'application a 5 "pages":
```suggestion
Pour ce chapitre, nous utiliserons l'application *Bibliothèque personnelle* comme exemple fil rouge. Outre l'`AppComponent` qui contient un `NavbarComponent`, l'application a 5 "pages":
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le routage ciblé de l'exemple d'application est le suivant :
```suggestion
Le routage cible de l'application-exemple est le suivant :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Dans Angular, la meilleure pratique consiste à charger et à configurer le routeur dans un module de niveau supérieur distinct, dédié au routage et importé par la racine `AppModule`. Par convention, l
```suggestion
Dans Angular, une bonne pratique consiste à charger et à configurer le routeur dans un module distinct de premier niveau, dédié au routage et importé par la racine `AppModule`. Par convention, le nom de classe du module est `AppRoutingModule` et il se situe dans le fichier `app-routing.module.ts` dans le dossier `src/app`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +`--flat` signale à la CLI de ne pas créer de dossier pour le module de routage afin qu'il soit placé au même niveau que le fichier `app.module.ts` et `--module=app` signifie que le module de routage
```suggestion
`--flat` signale au CLI de ne pas créer de dossier pour le module de routage afin qu'il soit placé au même niveau que le fichier `app.module.ts` et `--module=app` signifie que le module de routage est à ajouter aux importations du `AppModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le `AppRoutingModule` généré ressemble à ceci :
```suggestion
L'`AppRoutingModule` généré ressemble à ceci :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le tableau `routes` est l'endroit où nous indiquons au `routeur` quel composant doit être affiché lorsque l'utilisateur clique sur un lien ou entre une URL dans la barre d'adresse.
```suggestion
Le tableau `routes` est l'endroit où nous indiquons au `routeur` quel composant doit être affiché lorsque l'utilisateur clique sur un lien ou tape une URL dans la barre d'adresse.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Une [Route](https://angular.io/api/router/Route) est principalement définie par un chemin et un composant. Il peut également définir une redirection, des routes enfants, une stratégie de correspondan
```suggestion
Une [Route](https://angular.io/api/router/Route) est principalement définie par un chemin et un composant. Elle peut également définir une redirection, des routes enfants, une stratégie de correspondance de chemin (path match strategy), des guards, des resolvers, des routes enfants lazy-loaded, etc...
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Voici un exemple d'application avec un tableau de bord sécurisé avec authentification :
```suggestion
Voici un exemple d'application avec un tableau de bord sécurisé par authentification :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- `canActivate` vous permet de définir des gardes de route. Une garde de route bloque l'activation de la route si la condition qu'elle définit n'est pas vérifiée.
```suggestion
- `canActivate` vous permet de définir des route guards. Un route guard bloque l'activation de la route si la condition qu'il définit n'est pas vérifiée.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- `'**'`: est un caractère générique qui signifie qu'il correspond à n'importe quelle URL
```suggestion
- `'**'`: est une wildcard qui signifie que le chemin correspond à n'importe quelle URL
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- détail du livre avec id 1 : `/books/1`
```suggestion
- détail du livre avec dont l'id est 1 : `/books/1`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- liste des auteurs : liste des livres : `/authors`
Faut que je corrige ça côté anglais
```suggestion
- liste des auteurs : `/authors`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- détail de l'auteur avec l'identifiant 1 : liste des livres : `/authors/1`
Pareil ici
```suggestion
- détail de l'auteur dont l'id 1 : `/authors/1`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +- tout autre route doit conduire à la page d'accueil
```suggestion
- toute autre route doit conduire à la page d'accueil
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Lors de l'utilisation de `ng serve`, Angular démarre automatiquement un serveur de développement configuré spécifiquement pour les spécificités d'un SPA. Dans un environnement de production, vous dev
```suggestion
Lors de l'utilisation de `ng serve`, Angular démarre automatiquement un serveur de développement configuré pour les spécificités d'une SPA. Dans un environnement de production, vous devrez configurer un serveur tel qu'un Nginx. Pour que le routage fonctionne correctement, la configuration du serveur doit avoir une règle de réécriture afin que le fichier `index.html` (produit en construisant l'application) soit servi pour toutes les "routes". Sinon, l'utilisateur rencontrerait une erreur 404. Pour Nginx, voici à quoi cela pourrait ressembler :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +C'est le but du `RouterOutlet`. Le `NavbarComponent` doit rester affiché à tout moment, ce qui signifie que les composants doivent être insérés en dessous. Ajoutons le `router-outlet` dans le `AppCom
```suggestion
C'est le but du `RouterOutlet`. Le `NavbarComponent` doit rester affiché à tout moment, ce qui signifie que les composants doivent être insérés en dessous. Ajoutons le `router-outlet` dans l'`AppComponent`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le `RouterOutlet` est l'une des directives de routeur qui sont devenues disponibles pour le `AppComponent` car `AppModule` importe `AppRoutingModule` qui a exporté `RouterModule`.
```suggestion
Le `RouterOutlet` est l'une des directives du routeur qui sont devenues disponibles dans l'`AppComponent` car l'`AppModule` importe l'`AppRoutingModule` qui, lui, exporte le `RouterModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Habituellement, une destination de lien est spécifiée via l'attribut `href`. Cependant, ce n'est pas la voie à suivre pour la navigation au sein d'un SPA et ne doit être utilisé que pour la navigatio
```suggestion
Habituellement, la destination d'un lien est spécifiée via l'attribut `href`. Cependant, ce n'est pas la voie à suivre pour la navigation au sein d'une SPA et ne doit être utilisé que pour la navigation vers des URL externes. En effet, naviguer via href dans une SPA fait recharger l'ensemble de l'application, ce qui est très inefficace et offre une très mauvaise expérience utilisateur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +
```suggestion

::: details Correction

```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +La directive `RouterLink` a un `Query Params` `Input`. Cet `Input` permet de passer des paramètres facultatifs via des chaînes de requête dans l'URL :
```suggestion
La directive `RouterLink` a un `queryParams` `Input`. Cet `Input` permet de passer des paramètres facultatifs via des queries dans l'URL :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +La navigation en cliquant sur les liens dans le `NavbarComponent` est maintenant fonctionnelle ; cependant, il n'y a aucun retour à l'utilisateur concernant le lien actif. C'est le but de la directiv
```suggestion
La navigation en cliquant sur les liens dans le `NavbarComponent` est maintenant fonctionnelle ; cependant, il n'y a rien d'afficher à l'utilisateur concernant quel lien est actif. C'est le but de la directive `routerLinkActive`. Elle vous permet de spécifier une ou plusieurs classes CSS à ajouter à l'élément lorsque la route liée est active.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +## Services de routeur
```suggestion
## Services du Router
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Jusqu'à présent, nous avons principalement travaillé avec le "Router" Angular du template. La bibliothèque fournit également des services pour interagir avec elle à partir d'une classe de composants.
```suggestion
Jusqu'à présent, nous avons principalement travaillé avec le `Router` Angular à partir du template. La librairie fournit également des services pour interagir avec elle à partir de la classe d'un composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Le service `ActivatedRoute` décrit l'état actuel du *routeur*. Grâce à lui, le composant associé à la route actuelle peut extraire des informations de l'URL via les propriétés `paramMap` et `queryPar
```suggestion
Le service `ActivatedRoute` décrit l'état actuel du *router*. Grâce à lui, le composant associé à la route actuelle peut extraire des informations de l'URL via les propriétés `paramMap` et `queryParamMap`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +`paramMap` et `queryParamMap` sont des Observables, une notion que nous verrons plus en détail dans un chapitre ultérieur. Observable permet d'observer comment les informations évoluent dans le temps
```suggestion
`paramMap` et `queryParamMap` sont des Observables, une notion que nous verrons plus en détail dans un chapitre ultérieur. Un Observable permet d'observer comment les informations évoluent dans le temps. Le service `ActivatedRoute` fournit également une propriété `snapshot` pour obtenir uniquement l'état du routeur à un moment donné. Cette propriété est suffisante pour couvrir la plupart des cas.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Les propriétés `paramMap` et `queryParamMap` sont `Observables` en raison des optimisations. En effet, lorsqu'on navigue sur la même route mais avec des paramètres différents (e.g. /books/123 => /boo
```suggestion
Les propriétés `paramMap` et `queryParamMap` sont des `Observables` à cause d'optimisations. En effet, lorsqu'on navigue sur la même route mais avec des paramètres différents (e.g. /books/123 => /books/456), Angular ne recharge pas le composant mais propage les nouveaux paramètres via ces `Observables`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +Qu'est-ce que ça veut dire ? Si vous autorisez uniquement la navigation vers la même route via la barre d'adresse, vous êtes couvert lors de l'utilisation de snapshot. Cependant, si vous fournissez u
```suggestion
Qu'est-ce que ça veut dire ? Si vous ne permettez la navigation vers la même route que via la barre d'adresse, vous pouvez utiliser snapshot sans risque. Cependant, si vous fournissez un moyen de naviguer vers la même route via un lien (comme un mécanisme "Suivant" et "Précédent"), vous devez écouter les modifications de `paramMap`/`queryParamMap`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +### Service de routeur
```suggestion
### Service Router
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +1. Lors de la configuration initiale du projet, la CLI a demandé si elle devait ajouter le routage Angular et nous avons répondu oui. La CLI a installé la bibliothèque `@angular/router`, vous pouvez
```suggestion
1. Lors de la configuration initiale du projet, le CLI a demandé si il devait ajouter le routage Angular et nous avons répondu oui. Le CLI a installé la librairie `@angular/router`, vous pouvez le vérifier dans les dépendances déclarées dans le `package.json`. Il a également créé le fichier `app-routing.module.ts`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +2. Ajoutez une route `login` liée au `LoginFormComponent` et une route `search` liée à `FilmSearchComponent` dans le fichier `app-routing.module.ts`.
```suggestion
2. Ajoutez une route `login` liée au `LoginFormComponent` et une route `search` liée au `FilmSearchComponent` dans le fichier `app-routing.module.ts`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +4. Remplacer le commutateur entre le `LoginFormComponent` et le `FilmSearchComponent` actuellement basé sur un `*ngIf` par une navigation d'une route à une autre. Vous devrez injecter le service Rout
```suggestion
4. Remplacez l'affichage conditionnel des `LoginFormComponent` et `FilmSearchComponent` actuellement basé sur un `*ngIf` par une navigation d'une route à une autre. Vous devrez injecter le service Router dans le LoginFormComponent.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> + **Question:** Pouvez-vous repérer un problème dans le fonctionnement de notre implémentation actuelle en ce qui concerne les problèmes de sécurité ?
```suggestion
 **Question:** Pouvez-vous repérer un problème dans le fonctionnement de notre implémentation actuelle en ce qui concerne la sécurité ?
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +6. **Bonus:** Créez un `NotFoundComponent` (404) avec CLI et ajoutez une route générique `'**'` qui redirige vers celui-ci. Le code ci-dessous est une proposition du contenu du composant 404. Ajoutez
```suggestion
6. **Bonus:** Créez un `NotFoundComponent` (404) avec le CLI et ajoutez une route générique `'**'` qui redirige vers celui-ci. Le code ci-dessous est une proposition du contenu du composant 404. Ajoutez un `routerLink` sur la balise `<a>` pour revenir au composant de recherche.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +7. **Bonus:** En savoir plus sur les [gardes de navigation](https://angular.io/api/router/CanActivate) pour sécuriser les routes. Nous allons en implémenter un dans le chapitre suivant.
```suggestion
7. **Bonus:** Apprenez-en plus sur les [navigation guards](https://angular.io/api/router/CanActivate) pour sécuriser les routes. Nous allons en implémenter un dans le chapitre suivant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Avec les composants et les directives, les services sont l'un des principaux éléments constitutifs d'une application Angular.
```suggestion
Avec les composants et les directives, les services sont l'un des principaux blocs de construction d'une application Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +La création d'un service avec CLI se fait comme suit :
```suggestion
La création d'un service avec le CLI se fait comme suit :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Cela créera le service et sa classe de test associée dans le dossier `app/services`. Il est courant de placer les services dans un dossier de services, CLI créera le dossier s'il n'existe pas déjà.
```suggestion
Cela créera le service et sa classe de test associée dans le dossier `app/services`. Il est courant de placer les services dans un dossier de services, le CLI créera le dossier s'il n'existe pas déjà.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Déclarez toujours une dépendance à un service comme privée. En effet le template ne doit jamais accéder directement à un service mais toujours passer par une propriété ou une méthode exposée par la c
```suggestion
Déclarez toujours une dépendance à un service comme privée. En effet le template ne devrait jamais accéder directement à un service mais toujours passer par une propriété ou une méthode exposée par la classe composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Dans le chapitre précédent, nous avons injecté des services fournis par la bibliothèque `@angular/router` dans les composants qui en ont besoin. Si vous êtes familier avec Spring, vous n'y avez peut-
```suggestion
Dans le chapitre précédent, nous avons injecté des services fournis par la librairie `@angular/router` dans les composants qui en ont besoin. Si vous êtes familier avec Spring, vous n'y avez peut-être pas beaucoup réfléchi car c'est l'un des mécanismes du framework.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Au démarrage, Angular crée un injecteur à l'échelle de l'application. Si d'autres injecteurs sont nécessaires, Angular les créera en cours de route. L'injecteur crée des dépendances (le plus souvent
```suggestion
Au démarrage, Angular crée un injecteur à l'échelle de l'application. Si d'autres injecteurs sont nécessaires, Angular les créera en cours de route. L'injecteur crée des dépendances (le plus souvent sous forme de services) et maintient un conteneur d'instances de dépendances qu'il réutilise si possible. L'injecteur obtient les informations sur la façon de créer ou de récupérer une dépendance auprès d'un fournisseur (provider). Un service agit généralement comme son propre fournisseur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Vous ne l'avez peut-être pas réalisé, mais nous avons déjà fait appel à des fournisseurs. Dans le chapitre Pipe, pour utiliser le `UpperCasePipe` dans la classe du composant plutôt que dans le templa
```suggestion
Vous ne l'avez peut-être pas réalisé, mais nous avons déjà fait appel à des fournisseurs. Dans le chapitre sur les pipes, pour utiliser le `UpperCasePipe` dans la classe du composant plutôt que dans le template, nous l'avons ajouté au tableau des providers du composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Lorsque Angular découvre qu'un composant dépend d'un service, il vérifie d'abord si l'injecteur a des instances existantes de ce service. Si une instance de service demandée n'existe pas encore, l'in
```suggestion
Lorsque Angular découvre qu'un composant dépend d'un service, il vérifie d'abord si l'injecteur a une instance existante de ce service. Si une instance du service demandé n'existe pas encore, l'injecteur en crée une à l'aide du provider enregistré et l'ajoute à l'injecteur avant de renvoyer le service à Angular. Lorsque tous les services demandés ont été résolus et renvoyés, Angular peut appeler le constructeur du composant avec ces services comme arguments.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +- **root level:** c'est le comportement par défaut lors de la création d'un service avec CLI. C'est ce que signifie `providedIn: 'root'`. La *même instance* de la dépendance est injectée partout où e
```suggestion
- **au niveau root:** c'est le comportement par défaut lors de la création d'un service avec le CLI. C'est ce que signifie `providedIn: 'root'`. La *même instance* de la dépendance est injectée partout où elle est nécessaire comme s'il s'agissait d'un singleton.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +- **module level:** la dépendance est ajoutée au tableau des fournisseurs du `NgModule`. Le module obtient sa propre instance de la dépendance
```suggestion
- *au niveau du module:** la dépendance est ajoutée au tableau de providers du `NgModule`. Le module obtient sa propre instance de la dépendance
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +- **component level:** la dépendance est ajoutée au tableau des fournisseurs du composant. Chaque instance de ce composant obtient sa propre instance de la dépendance.
```suggestion
- **au niveau du composant:** la dépendance est ajoutée au tableau des providers du composant. Chaque instance de ce composant obtient sa propre instance de la dépendance.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +1. Générez un `AuthenticationService` avec CLI dans le dossier `app/services`
```suggestion
1. Générez un `AuthenticationService` avec le CLI dans le dossier `app/services`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +2. Déplacez la logique `loggedIn` de `AppComponent` vers le service
```suggestion
2. Déplacez la logique du `loggedIn` de l'`AppComponent` vers le service
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +3.Injectez le service dans le `LoginFormComponent` et utilisez-le.
```suggestion
3. Injectez le service dans le `LoginFormComponent` et utilisez-le.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +4. Implémentez une méthode de déconnexion dans le service d'authentification et ajoutez un bouton de déconnexion dans le `AppComponent` qui l'appelle et retourne au `LoginFormComponent`. Voici le htm
```suggestion
4. Implémentez une méthode de déconnexion dans le service d'authentification et ajoutez un bouton de déconnexion dans l'`AppComponent` qui l'appelle et provoque une navigation vers le `LoginFormComponent`. Voici l'html et le css :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +6. Utilisez la navigation guard pour rediriger l'utilisateur qui souhaite accéder à la page de recherche de films vers `/login` s'il n'est pas authentifié (rendez le CanActivate vrai si la route est
```suggestion
6. Utilisez un navigation guard pour rediriger l'utilisateur qui souhaite accéder à la page de recherche de films vers `/login` s'il n'est pas authentifié (rendez le CanActivate vrai si la route est accessible sinon retournez un `UrlTree` via la méthode `createUrlTree` du service `Router`). Pour prendre en considération des cas d'usage futur, ajoutez un returnUrl en tant que queryParam au `UrlTree` renvoyé afin que le `LoginFormComponent` sache où revenir après l'authentification et modifiez le `LoginFormComponent` en conséquence. Pour générer le navigation guard, utilisez la commande duCLI suivante :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Les méthodes du service `HttpClient` renvoient des Observables. Ils seront traités dans le prochain chapitre sur la bibliothèque RxJS. Un Observable n'est exécuté qu'une fois souscrit via la méthode
```suggestion
Les méthodes du service `HttpClient` renvoient des Observables. Ils seront traités dans le prochain chapitre sur la librairie RxJS. Un Observable n'est exécuté qu'une fois souscrit via la méthode `subscribe`. La méthode subscribe s'attend à ce qu'au moins une callback lui soit passé. La callback est le plus souvent fournie sous forme d'une fonction flèche (arrow function).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Le proxy détournera tous les appels pour http://localhost:4200/api vers le serveur exécuté sur https://vue-js-backend.herokuapp.com. Cela garantit également que nous ne rencontrons aucun problème COR
```suggestion
Le proxy détournera tous les appels à l'URL commençant par http://localhost:4200/api vers le serveur disponible à l'adresse https://vue-js-backend.herokuapp.com. Cela garantit également que nous ne rencontrerons aucun problème lié aux CORS. Cette configuration concerne uniquement le serveur de développement webpack fourni par le CLI pour exécuter l'application sur votre machine dans un environnement de développement. Ce ne sera pas la configuration utilisée en production.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +3. Dans le fichier de configuration CLI - `angular.json` - ajoutez l'option `proxyConfig` à la cible de service :
```suggestion
3. Dans le fichier de configuration CLI - `angular.json` - ajoutez l'option `proxyConfig` à la target serve :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +Notez le token dans la `UserResponse`, il servira à authentifier l'utilisateur via l'entête Authorization : `Authorization: Bearer <token>`. En savoir plus sur JWT [ici](https://jwt.io/introduction).
```suggestion
Prenez note du token dans la `UserResponse`, il servira à authentifier l'utilisateur via l'entête Authorization : `Authorization: Bearer <token>`. Apprenez-en plus sur les JWT [ici](https://jwt.io/introduction).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +7. La modification de la signature d'appel de la méthode `login` nécessitera un peu de refactorisation dans le `LoginFormComponent` :
```suggestion
7. La modification de la signature d'appel de la méthode `login` va nécessiter un peu de refactorisation dans le `LoginFormComponent` :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +9. Ajoutez un bouton d'enregistrement à côté du bouton de connexion dans le `LoginFormComponent`, donnez-lui l'attribut `type="button"` afin qu'Angular sache que ce n'est pas ce bouton qui déclenche
```suggestion
9. Ajoutez un bouton d'enregistrement à côté du bouton de connexion dans le `LoginFormComponent`, donnez-lui l'attribut `type="button"` afin qu'Angular sache que ce n'est pas ce bouton qui déclenche l'événement `ngSubmit` sur le formulaire et faites-lui appeler le méthode d'enregistrement. Vous devriez maintenant pouvoir enregistrer un utilisateur et vous connecter.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +10. Il est temps de gérer les erreurs. La méthode subscription peut recevoir trois rappels : un suivant, une erreur et un complet (nous verrons cela plus en détail dans le chapitre suivant). Passez l
```suggestion
10. Il est temps de gérer les erreurs. La méthode subscribe peut recevoir trois callbacks: une next, une error et une complete (nous verrons cela plus en détail dans le chapitre suivant). Passez la méthode `errorHandler` comme callback error à la méthode subscribe de la connexion et de l'enregistrement, vous devrez déclarer un champ `errorMessage` sur le `LoginFormComponent`. Afficher le message d'erreur sur le formulaire.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +a. Utilisez CLI pour en générer un : `ng generate interceptor interceptors/authentication`.
```suggestion
a. Utilisez le CLI pour en générer un : `ng generate interceptor interceptors/authentication`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +S'il y a un token dans le `AuthenticationService`, l'intercepteur l'ajoutera aux en-têtes de la requête http.
```suggestion
S'il y a un token dans l'`AuthenticationService`, l'intercepteur l'ajoutera aux en-têtes de la requête http.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +c. Ajouter l'intercepteur aux fournisseurs du `AppModule`
```suggestion
c. Ajouter l'intercepteur aux providers de l'`AppModule`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +1.  Créez un `FilmService` à l'aide de CLI et implémentez l'appel au point de terminaison `api/movies/search`. Notez que le queryParam `title` n'est pas facultatif. Pour ajouter des paramètres de req
```suggestion
12.  Créez un `FilmService` à l'aide du CLI et implémentez l'appel au endpoint `api/movies/search`. Notez que le queryParam `title` n'est pas facultatif. Pour ajouter des query param sà une requête, utilisez le paramètre `options` de la méthode get.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +13. Vérifiez que le token est envoyé sous forme d'en-tête HTTP via les outils de développement de votre navigateur.
```suggestion
14. Vérifiez que le token est envoyé sous forme d'en-tête HTTP via les outils de développement de votre navigateur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +13. Apportez des modifications au `FilmSearchComponent` pour appeler ce nouveau service avec le titre rempli par l'utilisateur, enregistrez la réponse au champ `films` dans le `FilmSearchComponent`.
```suggestion
13. Apportez des modifications au `FilmSearchComponent` pour appeler ce nouveau service avec le titre renseigné par l'utilisateur, enregistrez la réponse dans le champ `films` du `FilmSearchComponent`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +14. **Bonus :** Modifiez la méthode de déconnexion `AuthenticationService` pour qu'elle définisse le token sur `null`.
```suggestion
15. **Bonus :** Modifiez la méthode de déconnexion `AuthenticationService` pour qu'elle passe le token à `null`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +[RxJS](https://v6.rxjs.dev/guide/overview) est une bibliothèque de programmation réactive utilisant Observables. Cela facilite la composition de code asynchrone ou basé sur un callback. Il fait parti
```suggestion
[RxJS](https://v6.rxjs.dev/guide/overview) est une librairie de programmation réactive utilisant les Observables. Cela facilite la composition de code asynchrone ou basé sur des callbacks. Elle fait partie de la collection [ReactiveX](http://reactivex.io/) de librairies open source (RxJava, RxSwift, Rx.NET, RxScala...). Elles partagent toutes une API très similaire, ce qui signifie que le transfert des compétences Rx d'un langage à un autre est très facile.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Le modèle ReactiveX `Observable` vous permet de traiter des flux d'événements asynchrones avec le même type d'opérations simples et composables que vous utilisez pour des collections d'éléments de do
```suggestion
Le modèle ReactiveX d'`Observable` vous permet de traiter des flux d'événements asynchrones avec le même type d'opérations simples et composables que vous utilisez pour des collections d'éléments de données comme des tableaux, des opérations telles que `filter`, `map`, `flatMap`, ` reduce` et bien d'autres. Il vous libère d'enchevêtrements de callbacks et rend ainsi votre code plus lisible et moins sujet aux bugs.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +La bibliothèque fournit le type `Observable` ainsi que des fonctions utilitaires pour :
```suggestion
La librairie fournit le type `Observable` ainsi que des fonctions utilitaires pour :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Ce chapitre n'entrera pas en profondeur sur les concepts de Rx, vous pouvez vous référer à la documentation officielle à cet effet. Cependant, il illustrera des situations courantes rencontrées dans
```suggestion
Ce chapitre n'entrera pas en profondeur dans les concepts de Rx, vous pouvez vous référer à la documentation officielle à cet effet. Cependant, il illustrera des situations courantes rencontrées dans les applications Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- La méthode d'abonnement prend trois callbacks en paramètres : next, error and complete
```suggestion
- La méthode subscribe prend trois callbacks en paramètres : next, error and complete
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Le `Observable` déclenche 3 notifications suivantes suivies d'une notification complète. Observable arrête d'émettre des valeurs parce qu'elles sont erronées ou parce qu'elles se terminent. Les deux
```suggestion
L'`Observable` déclenche 3 notifications next suivies d'une notification complete. Un Observable arrête d'émettre des valeurs parce qu'elles sont erronées (callback error) ou parce qu'elles se terminent (callback complete). Les deux événements s'excluent mutuellement.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Dans une application Angular, vous aurez rarement à créer vous-même des observables. La plupart du temps, vous gérerez les flux que le framework a créés pour vous, tels que la gestion des résultats d
```suggestion
Dans une application Angular, vous aurez rarement à créer vous-même des observables. La plupart du temps, vous gérerez les flux que le framework a créés pour vous, tels que la gestion des résultats d'appels http, l'écoute d'événements du routeur ou l'écoute d'événements de formulaire lors de l'utilisation du `ReactiveFormsModule` (le nom du module révèle sa nature réactive). Cependant, vous pouvez rencontrer des situations où il peut vous incomber de créer un flux. Voici les principales façons dont cela pourrait se produire.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- transformation promise ([marble](https://rxmarbles.com/#from) / [documentation](https://v6.rxjs.dev/api/index/function/from))
```suggestion
- transformation de promesse ([marble](https://rxmarbles.com/#from) / [documentation](https://v6.rxjs.dev/api/index/function/from))
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- transformation d'événement de navigateur ([documentation](https://v6.rxjs.dev/api/index/function/fromEvent))
```suggestion
- transformation d'événement du navigateur ([documentation](https://v6.rxjs.dev/api/index/function/fromEvent))
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Semblable à la fonction bien connue `Array.prototype.map`, l'opérateur `map` ([marble](https://rxmarbles.com/#map) / [documentation](https://v6.rxjs.dev/api/operators/map)) applique une projection à
```suggestion
Semblable à la fonction bien connue `Array.prototype.map`, l'opérateur `map` ([marble](https://rxmarbles.com/#map) / [documentation](https://v6.rxjs.dev/api/operators/map)) applique une projection à chaque valeur et émet cette projection dans l'`Observable` de sortie.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Similaire à la fonction `Array.prototype.filter`, l'opérateur `filter` ([marble](https://rxmarbles.com/#filter) / [documentation](https://v6.rxjs.dev/api/operators/filter)) filtre les éléments émis p
```suggestion
Similaire à la fonction `Array.prototype.filter`, l'opérateur `filter` ([marble](https://rxmarbles.com/#filter) / [documentation](https://v6.rxjs.dev/api/operators/filter)) filtre les éléments émis par l'Observable source en n'émettant que ceux qui satisfont un prédicat spécifié.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Comme vu précédemment, la méthode `subscribe` prend un callback `error`. Lorsque `Observable` sort une erreur, il est exécuté à la place du callback `next` et `Observable` cesse d'émettre.
```suggestion
Comme vu précédemment, la méthode `subscribe` prend un callback `error`. Lorsque l'`Observable` sort une erreur, il est exécuté à la place du callback `next` et l'`Observable` cesse d'émettre.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +## Composition du flux
```suggestion
## Composition de flux
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Il est assez courant de devoir enchaîner les appels backend. Par exemple, l'utilisateur vient de modifier une ressource et vous souhaitez que votre page affiche ses détails mis à jour. Certains backe
```suggestion
Il est assez courant de devoir enchaîner les appels backend. Par exemple, l'utilisateur vient de modifier une ressource et vous souhaitez que votre page affiche ses détails mis à jour. Certains backends renvoient les détails de la ressource mise à jour dans le corps de la réponse à l'appel d'édition. Cependant, certains renvoient simplement une réponse HTTP 200 ou 204 sans corps. Cela signifie que l'appel de modification et l'appel de détail doivent être chaînés pour mettre à jour l'interface utilisateur. RxJS fournit plusieurs opérateurs pour enchaîner les événements de manière déclarative. Nous utiliserons l'opérateur `switchMap` ([documentation](https://rxjs.dev/api/operators/switchMap) / [marble](https://rxmarbles.com/#switchMap)) dans ce cas. Vous pouvez l'essayer dans le Stackblitz ci-dessous (cliquez n'importe où sur l'aperçu et voyez ce qu'il se passe dans la console, cliquez à nouveau et voyez comment les choses changent dans la console).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +**Question : A partir de cet exemple, qu'apprenez-vous sur le fonctionnement de switchMap ? (Regarder le diagramme en marbre peut aider)**
marble fait plutôt référence aux billes ici
```suggestion
**Question : A partir de cet exemple, qu'apprenez-vous sur le fonctionnement de switchMap ? (Regarder le diagramme marble peut aider)**
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Un piège très courant avec RxJS est d'imbriquer des abonnés. RxJS fournit de nombreux opérateurs afin que vous n'ayez jamais à mélanger du code synchrone et asynchrone.
```suggestion
Un piège très courant avec RxJS est d'imbriquer des subscribes. RxJS fournit de nombreux opérateurs afin que vous n'ayez jamais à mélanger du code synchrone et asynchrone.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> + - il est difficile de composer des observables,
```suggestion
 - cela rend difficile de composer des observables,
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Le plus souvent, cela se fait sans s'en rendre compte. Par exemple, dans le prochain callback d'un asubscribe, vous appelez une méthode qui a un subscribe. C'est l'imbrication des subscribes.
```suggestion
Le plus souvent, on le fait sans s'en rendre compte. Par exemple, dans la callback next d'un subscribe, vous appelez une méthode qui a un subscribe. C'est de l'imbrication de subscribes.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Pour le moment nous avons vu comment subscribe à Observables. Pour éviter les fuites de mémoire avec les Observables de longue durée, vous devez vous unsubscribe d'eux.
```suggestion
Pour le moment nous avons vu comment subscribe à un Observable. Pour éviter les fuites de mémoire avec les Observables de longue durée, vous devez vous unsubscribe de leur flux.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Réutilisons notre exemple de routage précédent pour illustrer comment les fuites de mémoire peuvent se produire. Un intervalle Observable est créé dans la méthode ngOnInit du composant de détails du
```suggestion
Réutilisons notre exemple de routage précédent pour illustrer comment les fuites mémoire peuvent se produire. Un Observable interval est créé dans la méthode ngOnInit du composant de détails du livre.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Quand unsubscribe ? Si vous n'avez aucune certitude que `Observable` s'achèvera ou qu'il produira une erreur, vous devez unsubscribe manuellement. Le `HttpClient` complète toujours l'Observable qu'il
```suggestion
Quand unsubscribe ? Si vous n'avez aucune certitude que l'`Observable` s'achèvera ou qu'il produira une erreur, vous devez unsubscribe manuellement. Le `HttpClient` complète toujours l'Observable qu'il renvoie après avoir reçu une réponse. Donc, théoriquement, si vous ne rencontrez que des Observables du `HttpClient`, vous n'avez pas à unsubscribe. Dans les autres cas, **soyez prudent et unsubscribe**.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- La méthode`subscribe` renvoie un objet `Subscription` qui peut être supprimé en appelant la méthode unsubscribe sur celui-ci lorsque vous le souhaitez, généralement lorsque le composant dans lequel
```suggestion
- La méthode `subscribe` renvoie un objet `Subscription` qui dont la mémoire peut être désallouée en appelant la méthode unsubscribe sur celui-ci lorsque vous le souhaitez, généralement lorsque le composant dans lequel il réside est détruit.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- En utilisant l'opérateur `takeUntil` ([marble](https://rxmarbles.com/#takeUntil) / [documentation](https://v6.rxjs.dev/api/operators/takeUntil)) et un [`Subject` ](https://v6.rxjs.dev/guide/subject
```suggestion
- En utilisant l'opérateur `takeUntil` ([marble](https://rxmarbles.com/#takeUntil) / [documentation](https://v6.rxjs.dev/api/operators/takeUntil)) et un [`Subject` ](https://v6.rxjs.dev/guide/subject) qui est un type spécial d'`Obversable` sur lequel il est possible d'appeler les méthodes next(), error() et complete().
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Corrigons la fuite de mémoire de l'exemple précédent. Pour illustrer les deux techniques, l'intervalle Observable a également été ajouté au composant des détails de l'auteur :
```suggestion
Corrigons la fuite de mémoire de l'exemple précédent. Pour illustrer les deux techniques, l'Observable interval a également été ajouté au composant des détails de l'auteur :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Subscribing à un `Observable` et enregistrer la valeur dans une propriété du composant n'est pas le seul moyen d'afficher les valeurs de l'`Observable`. Angular fournit un tuyau auquel l'`Observable`
```suggestion
Invoquer la méthode subscribe sur un `Observable` et enregistrer la valeur dans une propriété du composant n'est pas le seul moyen d'afficher les valeurs de l'`Observable`. Angular fournit un pipe auquel l'`Observable` peut être transmis directement.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Aucun subscribe n'étant effectué, il n'est pas nécessaire de se unsubscribe. Le pipe async s'en charge pour nous.
```suggestion
Aucun subscribe n'étant effectué, il n'est pas nécessaire d'unsubscribe. Le pipe async s'en charge pour nous.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- Vous pouvez vous unsubscribe ou utilisez le pipe asynchrone
```suggestion
- Unsubscribe ou utilisez le pipe async
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- Ne jamais imbriquer les subscribes, trouver les bons opérateurs à la place
```suggestion
- N'imbriquez jamais les subscribes, trouvez plutôt les bons opérateurs
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +Il existe également deux constantes `Observable` : `NEVER` (n'émet ni valeurs ni erreurs ni la notification d'achèvement) et `EMPTY` (n'émet aucun élément et émet immédiatement une notification compl
```suggestion
Il existe également deux constantes `Observable` : `NEVER` (n'émet ni valeurs ni erreurs ni la notification complete) et `EMPTY` (n'émet aucun élément et émet immédiatement une notification complete). `EMPTY` est très utile comme valeur de retour de l'opérateur `catchError`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- Dans le fichier `film-search.component.ts`, arrêtez de vous subscribe à la réponse de recherche et utilisez plutôt un pipe asynchrone dans le template.
```suggestion
- Dans le fichier `film-search.component.ts`, arrêtez de subscribe à la réponse de recherche et utilisez plutôt un pipe async dans le template.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/rxjs/README.md
> +- Même si cela n'est pas strictement nécessaire dans ces cas, vous pouvez vous unsubscribe du login et enregistrez les appels dans le `LoginFormComponent` en utilisant la technique `Subject`.
```suggestion
- Même si cela n'est pas strictement nécessaire dans ces cas, vous pouvez vous unsubscribe des appels à login et register dans le `LoginFormComponent` en utilisant la technique `Subject`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Les formulaires permettent à l'application Web d'obtenir les entrées de l'utilisateur.
```suggestion
Les formulaires permettent à l'application Web d'obtenir des entrées utilisateur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Lorsque l'utilisateur soumet le formulaire, il est traité localement par l'application Web. Ce dernier peut choisir d'envoyer des données au serveur à l'aide du client HTTP.
```suggestion
Lorsque l'utilisateur soumet le formulaire, il est traité localement par l'application Web. Celle-ci peut choisir d'envoyer des données au serveur à l'aide du client HTTP.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Dans une application monopage (Single Page Application), les formulaires ne redirigent pas vers une page serveur lorsque l'utilisateur les publie (comme en PHP par exemple). Cependant, le SPA peut ré
```suggestion
Dans une SPA, les formulaires ne redirigent pas vers une page serveur lorsque l'utilisateur les publie (comme en PHP par exemple). Cependant, la SPA peut récupérer les données du formulaire à partir du template et les envoyer au serveur si nécessaire à l'aide d'un appel HTTP asynchrone.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Angular simplifie les tâches courantes liées à la création et au traitement des formulaires, telles que la liaison de données, la validation et l'envoi des données au serveur.
```suggestion
Angular simplifie les tâches courantes liées à la création et au traitement des formulaires, telles que le data-binding entre le template et la classe du composant, la validation et l'envoi des données au serveur.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- Formulaires Template-driven : simples à utiliser mais beaucoup moins évolutifs que les formulaires réactifs et conviennent parfaitement aux formulaires simples à une ou deux entrées avec peu ou pas
```suggestion
- Template-driven forms : simples à utiliser mais beaucoup moins scalables  que les formulaires réactifs et conviennent parfaitement aux formulaires simples à un ou deux inputs avec peu ou pas de règles de validation.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- Formes réactives : ont une courbe d'apprentissage abrupte mais offrent plus d'avantages en termes de gestion de cas d'utilisation complexes, d'évolutivité, de réutilisabilité et de testabilité. Leu
```suggestion
- Reactive forms : ont une courbe d'apprentissage abrupte mais offrent plus d'avantages en termes de gestion de cas d'utilisation complexes, de scalabilité, de réutilisabilité et de testabilité. Leur implémentation est basée sur RxJS.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +## Formulaires Template-driven
```suggestion
## Template-driven forms
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +L'entrée utilisateur peut être récupérée dans la classe du composant grâce à la directive `NgModel`. Comme vous vous en souvenez peut-être, nous l'avons utilisé dans le chapitre *Renforcez votre HTML
```suggestion
La valeur de l'input peut être récupérée dans la classe du composant grâce à la directive `NgModel`. Comme vous vous en souvenez peut-être, nous l'avons utilisé dans le chapitre *Dynamisez votre HTML* pour commander des glaces.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Voici un exemple qui utilise `[(ngModel)]` pour lier un champ `input` et `select`.
```suggestion
Voici un exemple qui utilise `[(ngModel)]` pour récupérer les valeurs d'un champ `input` et d'un champ `select`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +N'oubliez pas d'importer `FormsModule` lors de l'utilisation de formulaires Template-driven (formulaires basés sur des modèles)
```suggestion
N'oubliez pas d'importer `FormsModule` lors de l'utilisation des template-driven forms
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Si vous regroupez les champs du formulaire dans un élément `form` (ce que vous devriez absolument faire), vous pouvez profiter de ces belles possibilités :
```suggestion
Si vous regroupez les champs du formulaire dans un élément `form` (ce que vous devriez absolument faire), vous pourrez profiter de ces possibilités :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- Obtenez une référence à l'ensemble du formulaire en capturant `ngForm` (exemple : `#formRef="ngForm"`). Cela permet, par exemple, d'obtenir le statut de validité de l'ensemble du formulaire
```suggestion
- Obtenir une référence à l'ensemble du formulaire en capturant `ngForm` (exemple : `#formRef="ngForm"`). Cela permet, par exemple, d'obtenir le statut de validité de l'ensemble du formulaire
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- Écoutez l'événement de soumission du formulaire en utilisant `(ngSubmit)`
```suggestion
- Écouter l'événement de soumission du formulaire en utilisant `(ngSubmit)`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +**Exercice : ajoutez un champ de saisie qui doit avoir une longueur minimale de 5 caractères. Afficher le contenu de ce champ lors de la soumission du formulaire**
```suggestion
**Exercice : ajoutez un champ de saisie qui doit avoir une longueur minimale de 5 caractères. Affichez le contenu de ce champ lors de la soumission du formulaire**
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Les formulaires réactifs permettent de lier l'ensemble de l'élément de formulaire HTML à son homologue dans la classe de composant.
```suggestion
Les reactive forms permettent de lier l'ensemble de l'élément de formulaire HTML à son homologue dans la classe du composant.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +## Formulaires réactifs
Reactive forms

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Veuillez noter que `FormControl`, `FormGroup` et d'autres éléments de formulaire réactifs sont définis dans le `ReactiveFormsModule`.
```suggestion
Veuillez noter que `FormControl`, `FormGroup` et d'autres éléments des reactive forms sont définis dans le `ReactiveFormsModule`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +### Contrôle de formulaire
```suggestion
### Form control
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Le projet suivant réécrit le premier exemple de la section précédente à l'aide de formulaires réactifs. Ici, nous définissons les objets `FormControl` et les lions avec leur contrepartie sur le templ
```suggestion
Le projet suivant réécrit le premier exemple de la section précédente à l'aide d'un reactive form. Ici, nous définissons les objets `FormControl` et les lions à leur contrepartie dans le template avec `[formControl]`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Comme vous pouvez le constater dans le template, la valeur et le statut valide des contrôles de formulaire sont obtenus directement à partir de l'instance de contrôle de formulaire.
```suggestion
Comme vous pouvez le constater dans le template, la valeur et le statut valide des champs de formulaire sont obtenus directement à partir de l'instance de form control.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +N'oubliez pas d'importer le `ReactiveFormsModule` lors de l'utilisation des formulaires réactifs
```suggestion
N'oubliez pas d'importer le `ReactiveFormsModule` lors de l'utilisation des reactive forms
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +### Groupe de formulaires
```suggestion
### Form group
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Un `FormGroup` est une collection de contrôles de formulaire regroupés. Il se compose d'une instance `FormGroup` qui est liée dans le template à une balise `<form>` via l'attribut `[formGroup]`.
```suggestion
Un `FormGroup` est une collection de form controls regroupés. Il se compose d'une instance `FormGroup` qui est liée dans le template à une balise `<form>` via l'attribut `[formGroup]`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Le composant suivant définit un `FormGroup` qui contient des contrôles de formulaire et un autre groupe de formulaires. Il illustre de nombreux cas d'utilisation liés aux formulaires : obtenir la val
```suggestion
Le composant suivant définit un `FormGroup` qui contient des form controls et un autre form group. Il illustre de nombreux cas d'utilisation liés aux formulaires : obtenir la valeur du formulaire, son statut, définir des validateurs sur le form control ou dans le template, et accéder aux form group enfants à l'aide de la méthode [get](https://angular.io/api/forms/AbstractControl#get).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +### Générateur de formulaires
```suggestion
### Form builder
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Angular `ReactiveFormsModule` fournit une API plus simple pour créer des FormGroups et des FormControls via le service `FormBuilder`.
```suggestion
Le `ReactiveFormsModule` d'Angular fournit une API plus simple pour créer des FormGroups et des FormControls via le service `FormBuilder`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +L'extrait de code suivant montre comment convertir la déclaration FormGroup précédente à l'aide de l'API `FormBuilder`.
```suggestion
L'extrait de code suivant montre comment convertir la déclaration du FormGroup précédente à l'aide de l'API `FormBuilder`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +### Validation de formulaire réactif
```suggestion
### Validation de reactive form
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Le `ReactiveFormsModule` permet de définir des validateurs dans le code du composant ou en utilisant des attributs de validation HTML5 tels que `required` et `minlength`. Angular fournit des validate
```suggestion
Le `ReactiveFormsModule` permet de définir des validateurs dans le code du composant ou en utilisant des attributs de validation HTML5 tels que `required` et `minlength`. Angular fournit des validateurs intégrés tels que `Validators.required`, `Validators.min`, `Validators.pattern`, vous pouvez trouver une liste complète [ici] (https://angular.io/api/forms/Validators). Vous pouvez également définir des validateurs personnalisés ([tutoriel](https://angular.io/guide/form-validation#defining-custom-validators)).
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Lorsque vous utilisez des validateurs HTML5, Angular recommande de les combiner avec les validateurs `@angular/forms` intégrés.
```suggestion
Lorsque vous utilisez des validateurs HTML5, Angular recommande de les combiner avec les validateurs fournis par `@angular/forms`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Le composant suivant illustre l'utilisation de plusieurs validateurs sur un contrôle de formulaire ainsi que l'utilisation d'un validateur personnalisé.
```suggestion
Le composant suivant illustre l'utilisation de plusieurs validateurs sur un form control ainsi que l'utilisation d'un validateur personnalisé.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Angular ajoute et supprime automatiquement des styles spécifiques en fonction de l'état du formulaire. Par exemple, lorsqu'un contrôle/groupe de formulaire est invalide, Angular ajoute à son élément
```suggestion
Angular ajoute et supprime automatiquement des styles spécifiques en fonction de l'état du formulaire. Par exemple, lorsqu'un form control/group est invalide, Angular ajoute à son élément HTML la classe `.ng-invalid`. Lorsque le form control/group devient valide, Angular remplace la classe `.ng-invalid` par la classe `.ng-valid`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Lorsqu'un contrôle de formulaire devient invalide, le contrôle et ses contrôles parents auront la classe `.ng-invalid`. Si ce comportement n'est pas souhaité, vous pouvez utiliser des pseudo-classes
```suggestion
Lorsqu'un form control devient invalide, lui et ses controls parent se voient attribuer la classe `.ng-invalid`. Si ce comportement n'est pas souhaité, vous pouvez utiliser des pseudo-classes telles que `:not`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Le composant suivant montre un exemple de la façon de tirer parti de :
```suggestion
Le composant suivant montre comment tirer parti :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- classes `.ng-invalid` et `.ng-dirty`
```suggestion
- des classes `.ng-invalid` et `.ng-dirty`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- `:not` pseudo-classe pour cibler uniquement le contrôle.
```suggestion
- de la `:not` pseudo-classe pour cibler uniquement le form control.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +1. Stylisez le label et le texte d'erreur de chaque champ avec la classe `.error` lorsque le formulaire est invalide et que ce champ n'est pas valide (rappelez-vous l'attribut `[class]`)
```suggestion
3. Stylisez le label et le texte d'erreur de chaque champ avec la classe `.error` lorsque le formulaire est invalide et que ce champ n'est pas valide (rappelez-vous l'attribut `[class]`)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +## TP : Connexion et inscription avec des formulaires réactifs
```suggestion
## TP : Connexion et inscription avec des reactive forms
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +1. Implémentez le formulaire de connexion / inscription à l'aide de formulaires réactifs et du générateur de formulaire : remplacez le `[(ngModel)]` dans le modèle et supprimez le `email` et le `mot
```suggestion
1. Implémentez le formulaire de connexion / inscription à l'aide dereactive forms et du form builder : remplacez le `[(ngModel)]` dans le template et supprimez les propriétés `email` et `mot de passe` de la classe du `LoginFormComponent`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +2. Ajoutez le validateur requis (`Validators.required`) aux deux champs et affichez le texte `"Ce champ est requis"` à côté de chaque champ si le formulaire est sale et que ce champ a l'erreur `requi
```suggestion
2. Ajoutez le validateur required (`Validators.required`) aux deux champs et affichez le texte `"Ce champ est requis"` à côté de chaque champ si le formulaire a un statut dirty et que ce champ a l'erreur `required` :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +2. Désactivez les boutons Connexion et Inscription à l'aide de l'attribut `[disabled]` si le formulaire n'est pas valide.
```suggestion
4. Désactivez les boutons Connexion et Inscription à l'aide de l'attribut `[disabled]` si le formulaire n'est pas valide.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +3. Définissez un validateur personnalisé pour le champ de mot de passe qui refuse les mots de passe faibles. Nous considérerons qu'un mot de passe est fort s'il satisfait à toutes ces exigences :
```suggestion
5. Définissez un validateur personnalisé pour le champ de mot de passe qui refuse les mots de passe faibles. Nous considérerons qu'un mot de passe est fort s'il satisfait à toutes ces exigences :
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +Vous pouvez utiliser la méthode `test` sur chaque motif et lui passer la valeur du contrôle pour vérifier si le motif existe dedans. Ajoutez un texte d'erreur via la balise `<small>` dans le champ du
```suggestion
Vous pouvez utiliser la méthode `test` sur chaque pattern/regex et leur passer la valeur du form control pour vérifier si le pattern y est présent. Ajoutez un texte d'erreur via la balise `<small>` dans le champ du mot de passe qui indique si le formulaire est invalide et si le champ contient l'erreur `password.pattern`.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +- [Documentation des formulaires officiels d'Angular](https://angular.io/guide/forms-overview)
```suggestion
- [Documentation officielle des formulaires Angular](https://angular.io/guide/forms-overview)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +  {path: 'dashboard', component: DashboardComponent, canActivate: AuthenticationGuard},
```suggestion
  {path: 'dashboard', component: DashboardComponent, canActivate: [AuthenticationGuard]},
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/routage/README.md
> +];
```suggestion
  {path: '', pathMatch: 'full', redirectTo: '/home'},
  {path: '**', redirectTo: '/home'}
];
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +    public user: UserResponse,
```suggestion
    public user: User,
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +private errorHandler(error: HttpErrorResponse): void {
```suggestion
private errorHandler(errorResponse: HttpErrorResponse): void {
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +  this.errorMessage = error.error.error ?? `${error.status} - ${error.statusText}`
```suggestion
  this.errorMessage = errorResponse.error.error ?? `${errorResponse.status} - ${errorResponse.statusText}`
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +}
```suggestion
// subscribe syntax
this.authenticationService.login(this.loginRequest)
  .subscribe(
    response => {/* */},
    error => {/* */}
  )
}
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Par défaut, tous les `NgModule`s sont chargés avec impatience au démarrage de l'application. Pour les grandes applications, ce n'est pas optimal car des modules qui peuvent même ne pas être nécessair
```suggestion
Par défaut, tous les `NgModule`s sont chargés au démarrage de l'application (eagerly-loaded). Pour les grosses applications, ceci n'est pas optimal car des modules qui peuvent ne pas être nécessaires à l'utilisateur sont chargés, ralentissant le temps de démarrage de l'application. Le lazy-loading est un design pattern qui permet aux développeurs de déclarer des routes de manière à ce que le routeur ne charge les modules de fonctionnalités que si l'utilisateur y accède. Le lazy-loading peut également être utilisé à des fins de sécurité : il n'est pas toujours souhaitable que le code des zones sécurisées soit chargé dès le démarrage de l'application.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +## Directives d'attributs personnalisé [doc](https://angular.io/guide/attribute-directives#building-an-attribute-directive) et structurel [doc](https://angular.io/guide/structural-directives#creating
```suggestion
## Directives d'attributs personnalisées [doc](https://angular.io/guide/attribute-directives#building-an-attribute-directive) et structurel [doc](https://angular.io/guide/structural-directives#creating-a-structural-directive)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +## Les tableaux de formulaires [doc](https://angular.io/guide/reactive-forms#creating-dynamic-forms)
```suggestion
## Les form arrays [doc](https://angular.io/guide/reactive-forms#creating-dynamic-forms)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Nous avons déjà parlé de `FormGroup` et `FormControl`. Ces deux classes héritent de `AbstractControl`. Une troisième classe en hérite : `FormArray`. C'est le troisième élément constitutif des formes
```suggestion
Nous avons déjà parlé de `FormGroup` et `FormControl`. Ces deux classes héritent d'`AbstractControl`. Une troisième classe en hérite : `FormArray`. C'est le troisième élément constitutif des reactive forms. Le but de `FormArray` est de suivre la valeur et la validité d'un tableau d'`AbstractControl`s. C'est particulièrement utile lorsque le nombre de controls n'est pas connu au moment de la construction, par exemple, ils sont basés sur des données renvoyées par le backend ou, l'utilisateur a la possibilité de les ajouter dynamiquement. Prenez par exemple un formulaire qui vous permet de déclarer n'importe quel nombre d'adresses e-mail de backup pour votre compte, vous ne pouvez pas lier les form controls via leur nom aux inputs dans le template au moment du build de l'application.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +## Les résolveurs [Article de blog](https://javascript.plainenglish.io/angular-resolver-for-prefetching-data-angular-guards-resolve-40fda257d666)
```suggestion
## Les resolvers [Article de blog](https://javascript.plainenglish.io/angular-resolver-for-prefetching-data-angular-guards-resolve-40fda257d666)
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Il existe principalement deux manières de traiter une page fortement dépendante des données reçues du backend. Soit charger les données après le chargement de la page, ce qui nécessitera une concepti
```suggestion
Il existe principalement deux manières de traiter une page fortement dépendante des données reçues du backend. Soit charger les données après le chargement de la page, ce qui nécessitera que la page ait un design pour l'état de chargement et un pour l'état d'erreur, au cas où les données ne seraient jamais reçues. Ou charger les données avant de naviguer vers la page. Cette alternative a l'avantage de simplifier l'interface utilisateur et le code. C'est assez facile à implémenter avec le routeur Angular : un resolver doit être passé à l'attribut `resolve` de la route. L'article explique la mise en œuvre en détail.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Il est assez fréquent que les applications soient soit affichées dans la langue du navigateur, soit laissent le choix de la langue à l'utilisateur via un sélecteur (ou les deux). Angular fournit un m
```suggestion
Il est assez fréquent que les applications soient soit affichées dans la langue du navigateur, soit laissent le choix de la langue à l'utilisateur via un sélecteur (ou les deux). Angular fournit un moyen de gérer les traductions avec sa librairie d'internationalisation : `@angular/localize`. Voici la [documentation complète](https://angular.io/guide/i18n) sur la façon de localiser une application à l'aide de la méthode officielle.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Une autre solution avec une implémentation plus simple existe : utiliser la bibliothèque `ngx-translate`. Voici un [blog d'article](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-you
```suggestion
Une autre solution avec une implémentation plus simple existe : utiliser la librairie `ngx-translate`. Voici un [article de blog](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-angular-app-with-ngx-translate) bien détaillé à ce sujet.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +Vous vous êtes peut-être rendu compte que lors de la génération de classes avec CLI (si le flag `--skipTests` n'est pas fourni), elles sont livrées avec un fichier de test équivalent. La documentatio
```suggestion
Vous vous êtes peut-être rendu compte que lors de la génération de classes avec le CLI (si le flag `--skipTests` n'est pas fourni), elles sont générées avec un fichier de test companion. La documentation Angular fournit plusieurs guides sur la façon de gérer les tests.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/pour-aller-plus-loin/README.md
> +L'équipe Angular fournit un site Web fantastique (le [Guide de mise à jour de Angular](https://update.angular.io/)) pour mettre à jour les applications Angular. Après avoir choisi la version actuelle
```suggestion
L'équipe Angular fournit un site Web fantastique (le [Guide de mise à jour d'Angular](https://update.angular.io/)) pour mettre à jour les applications Angular. Après avoir choisi la version actuelle de votre application et la version cible, une liste détaillée de toutes les étapes nécessaires pour effectuer une mise à jour réussie est fournie.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/ecosysteme/README.md
> +- **[Angular.io](angular.io):** Le site officiel d'Angular. Ce site contient des TONNES de guides, références et de tutoriels dans lesquels vous pourriez passer des semaines à plonger.
```suggestion
- **[Angular.io](angular.io):** Le site officiel d'Angular. Ce site contient des TONNES de guides, références et de tutoriels dans lesquels vous pourriez passer des semaines à éplucher.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/ecosysteme/README.md
> +- **[Angular Material](material.angular.io/components) et [CDK](https://material.angular.io/cdk/categories):** Deux bibliothèques UI/UX développées et maintenues par l'équipe Angular Components qui f
```suggestion
- **[Angular Material](material.angular.io/components) et [CDK](https://material.angular.io/cdk/categories):** Deux librairies UI/UX développées et maintenues par l'équipe Angular Components qui fait partie de l'équipe Angular de Google. L'équipe comprend à la fois des employés de Google et des contributeurs de la communauté du monde entier. Angular Material contient des composants d'interface utilisateur de haute qualité qui peuvent être utilisés dans des applications existantes. Le CDK (Component Development Kit) vous aide à créer vos propres composants personnalisés avec des modèles d'interaction courants. Les deux librairies sont maintenues au même rythme que le framework Angular.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/ecosysteme/README.md
> +- **[RxJS](rxjs.dev):** En savoir plus sur les concepts de la bibliothèque en profondeur ici. Le site fournit également un arbre de décision pour vous aider à choisir le bon opérateur pour résoudre l
```suggestion
- **[RxJS](rxjs.dev):** Apprenez-en plus sur les concepts de la librairie ici. Le site fournit également un arbre de décision pour vous aider à choisir le bon opérateur pour résoudre la situation que vous rencontrez.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/ecosysteme/README.md
> +- **[MDN Web Docs](https://developer.mozilla.org/):** MDN Web Docs est une plate-forme d'apprentissage évolutive pour les technologies Web et les logiciels qui alimentent le Web, notamment CSS, HTML
```suggestion
- **[MDN Web Docs](https://developer.mozilla.org/):** MDN Web Docs est une plate-forme d'apprentissage évolutive pour les technologies Web et les logiciels qui font marcher le Web, notamment CSS, HTML et JavaScript. Elle offre d'excellentes ressources, je ne peux que la recommander.
```

2021-10-29 11:04 UTC, Ocunidee commented on docs/src/fr/ecosysteme/README.md
> +- **[Can I Use](https://caniuse.com/):** fournit des tableaux de prise en charge des navigateurs à jour pour la prise en charge des technologies Web frontales sur les navigateurs Web de bureau et mob
```suggestion
- **[Can I Use](https://caniuse.com/):** fournit des tableaux à jour de prise en charge des technologies Web par les navigateurs desktop et mobile.
```

2022-02-03 15:52 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +## Jouer autour
oups, j'ai fait moi-même une faute ici: Expérimenter

2022-02-03 16:02 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +Dans TypeScript, tout comme dans ECMAScript 2015 (ES6), tout fichier contenant une importation ou une exportation de niveau supérieur est considéré comme un module.
Espace en trop après export, my bad

2022-02-03 16:53 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +**Bonus: use an NgIf Else to conditionnally show either the data or the no data message**
montrer soit les données
 
 Typo: soir => soit

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/directives/README.md
> +**Bonus: utilisez un NgIf Else pour conditionnellement montrer soir les données soit le message comme quoi les données ne sont pas disponibles**
```suggestion
**Bonus: utilisez un NgIf Else pour conditionnellement montrer soit les données soit le message comme quoi les données ne sont pas disponibles**
```

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/formulaires/README.md
> +1. Implémentez le formulaire de connexion / inscription à l'aide dereactive forms et du form builder : remplacez le `[(ngModel)]` dans le template et supprimez les propriétés `email` et `mot de passe
```suggestion
1. Implémentez le formulaire de connexion / inscription à l'aide de reactive forms et du form builder : remplacez le `[(ngModel)]` dans le template et supprimez les propriétés `email` et `mot de passe` de la classe du `LoginFormComponent`.
```

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +6. Utilisez un navigation guard pour rediriger l'utilisateur qui souhaite accéder à la page de recherche de films vers `/login` s'il n'est pas authentifié (rendez le CanActivate vrai si la route est
```suggestion
6. Utilisez un navigation guard pour rediriger l'utilisateur qui souhaite accéder à la page de recherche de films vers `/login` s'il n'est pas authentifié (rendez le CanActivate vrai si la route est accessible sinon retournez un `UrlTree` via la méthode `createUrlTree` du service `Router`). Pour prendre en considération des cas d'usage futur, ajoutez un returnUrl en tant que queryParam au `UrlTree` renvoyé afin que le `LoginFormComponent` sache où revenir après l'authentification et modifiez le `LoginFormComponent` en conséquence. Pour générer le navigation guard, utilisez la commande du CLI suivante :
```

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +## Expérimeter
```suggestion
## Expérimenter
```

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/typescript/README.md
> +En TypeScript, tout comme dans ECMAScript 2015 (ES6), tout fichier contenant à son début un import ou un export  est considéré comme un module.
```suggestion
En TypeScript, tout comme dans ECMAScript 2015 (ES6), tout fichier contenant à son début un import ou un export est considéré comme un module.
```

2022-02-04 11:08 UTC, Ocunidee commented on docs/src/fr/services/README.md
> +12. Créez un `FilmService` à l'aide du CLI et implémentez l'appel au endpoint `api/movies/search`. Notez que le queryParam `title` n'est pas facultatif. Pour ajouter des query param sà une requête, u
```suggestion
12. Créez un `FilmService` à l'aide du CLI et implémentez l'appel au endpoint `api/movies/search`. Notez que le queryParam `title` n'est pas facultatif. Pour ajouter des query params à une requête, utilisez le paramètre `options` de la méthode get.
```

2022-02-04 11:13 UTC, Ocunidee approved these changes

2022-02-04 11:15 UTC, merged